// src/app/core/layout/app-layout.tsx
import { NavLink, Outlet } from 'react-router';
import { ConfirmDialog } from '../../shared/components/confirm-dialog';
import { usePermission, useServices } from '../di/services-context';
import { useSignal } from '../state/use-signal';
import './app-layout.css';

const navClass = ({ isActive }: { isActive: boolean }): string => (isActive ? 'active' : '');

export function AppLayout() {
  const { authService, toastService } = useServices();
  const profile = useSignal(authService.profile);
  const messages = useSignal(toastService.messages);

  const canViewCandidates = usePermission('view_candidates');
  const canManageCatalogs = usePermission('manage_catalogs');
  const canManageUsers = usePermission('manage_users');
  const canManageRoles = usePermission('manage_roles');
  const canImport = usePermission('import_candidates');

  return (
    <div className="shell">
      <a className="skip-link" href="#main-content">
        Saltar al contenido principal
      </a>
      <header>
        <div className="brand">
          <strong>Kepker Talento</strong>
          <span className="muted">Gestión interna de candidatos del ecosistema Kepker</span>
        </div>
        <nav aria-label="Navegación principal">
          <NavLink to="/app" end className={navClass}>
            Dashboard
          </NavLink>
          {canViewCandidates ? (
            <>
              <NavLink to="/app/candidates" className={navClass}>
                Candidatos
              </NavLink>
              <NavLink to="/app/search" className={navClass}>
                Búsqueda
              </NavLink>
            </>
          ) : null}
          {canManageCatalogs ? (
            <NavLink to="/app/catalogs" className={navClass}>
              Catálogos
            </NavLink>
          ) : null}
          {canManageUsers ? (
            <NavLink to="/app/admin/users" className={navClass}>
              Usuarios
            </NavLink>
          ) : null}
          {canManageRoles ? (
            <NavLink to="/app/admin/roles" className={navClass}>
              Roles
            </NavLink>
          ) : null}
          {canImport ? (
            <NavLink to="/app/admin/import" className={navClass}>
              Importación
            </NavLink>
          ) : null}
        </nav>
        <div className="user">
          <span className="badge">{profile?.role}</span>
          <button className="button secondary" type="button" onClick={() => authService.signOut()}>
            Salir
          </button>
        </div>
      </header>
      <main id="main-content" tabIndex={-1}>
        <Outlet />
      </main>
      <div className="toasts" role="region" aria-label="Notificaciones">
        {messages.map((message) => (
          <article className="toast" role="status" aria-live="polite" key={message.id}>
            <div>{message.text}</div>
            <button
              className="button ghost dismiss"
              type="button"
              onClick={() => toastService.dismiss(message.id)}
            >
              Cerrar
            </button>
          </article>
        ))}
      </div>
      <ConfirmDialog />
    </div>
  );
}

// src/app/core/layout/app-layout.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../auth/auth.service';
import { ToastService } from '../services/toast.service';
import { ConfirmDialogComponent } from '../../shared/components/confirm-dialog.component';

@Component({
  selector: 'rrhh-app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, ConfirmDialogComponent],
  styles: [
    `
      .shell {
        min-height: 100vh;
      }
      .skip-link {
        background: var(--fj-orange-bright);
        color: var(--fj-navy);
        left: 12px;
        padding: 8px 10px;
        position: absolute;
        top: -100px;
        z-index: 100;
      }
      .skip-link:focus {
        top: 8px;
      }
      header {
        align-items: center;
        background: var(--fj-navy);
        border-bottom: 1px solid var(--fj-navy-90);
        display: flex;
        gap: 18px;
        justify-content: space-between;
        min-height: 64px;
        padding: 0 22px;
      }
      .brand {
        display: grid;
        gap: 2px;
      }
      .brand strong {
        color: var(--bg-1);
        font-family: var(--font-display);
        font-size: 18px;
      }
      .brand .muted {
        color: var(--fg-3);
      }
      nav {
        display: flex;
        flex-wrap: wrap;
        gap: 6px;
      }
      nav a {
        border-left: 3px solid transparent;
        border-radius: var(--r-md);
        color: #d8dee8;
        font-family: var(--font-display);
        font-size: 13px;
        font-weight: 600;
        padding: 8px 10px;
        text-decoration: none;
      }
      nav a:hover {
        background: var(--fj-navy-90);
      }
      nav a.active {
        background: var(--fj-navy-90);
        border-left-color: var(--fj-orange-bright);
        color: var(--fj-orange-bright);
        font-weight: 700;
      }
      main {
        margin: 0 auto;
        max-width: 1180px;
        padding: 22px;
      }
      .user {
        align-items: center;
        display: flex;
        gap: 10px;
      }
      .user .badge {
        background: rgba(224, 132, 63, 0.15);
        color: var(--fj-orange-bright);
      }
      .toasts {
        bottom: 20px;
        display: grid;
        gap: 8px;
        position: fixed;
        right: 20px;
        width: min(360px, calc(100vw - 40px));
        z-index: 20;
      }
      .toast {
        background: var(--fj-navy);
        border-radius: var(--r-lg);
        color: white;
        display: grid;
        gap: 8px;
        padding: 12px;
      }
      .toast .dismiss {
        justify-self: end;
      }
    `,
  ],
  template: `
    <div class="shell">
      <a class="skip-link" href="#main-content">Saltar al contenido principal</a>
      <header>
        <div class="brand">
          <strong>Kepker Talento</strong>
          <span class="muted">Gestión interna de candidatos del ecosistema Kepker</span>
        </div>
        <nav aria-label="Navegación principal">
          <a
            routerLink="/app"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
          >
            Dashboard
          </a>
          @if (auth.hasPermission('view_candidates')) {
            <a routerLink="/app/candidates" routerLinkActive="active">Candidatos</a>
            <a routerLink="/app/search" routerLinkActive="active">Búsqueda</a>
          }
          @if (auth.hasPermission('manage_catalogs')) {
            <a routerLink="/app/catalogs" routerLinkActive="active">Catálogos</a>
          }
          @if (auth.hasPermission('manage_users')) {
            <a routerLink="/app/admin/users" routerLinkActive="active">Usuarios</a>
          }
          @if (auth.hasPermission('manage_roles')) {
            <a routerLink="/app/admin/roles" routerLinkActive="active">Roles</a>
          }
          @if (auth.hasPermission('import_candidates')) {
            <a routerLink="/app/admin/import" routerLinkActive="active">Importación</a>
          }
        </nav>
        <div class="user">
          <span class="badge">{{ auth.profile()?.role }}</span>
          <button class="button secondary" type="button" (click)="auth.signOut()">Salir</button>
        </div>
      </header>
      <main id="main-content" tabindex="-1">
        <router-outlet />
      </main>
      <div class="toasts" role="region" aria-label="Notificaciones">
        @for (message of toast.messages(); track message.id) {
          <article class="toast" role="status" aria-live="polite">
            <div>{{ message.text }}</div>
            <button class="button ghost dismiss" type="button" (click)="toast.dismiss(message.id)">
              Cerrar
            </button>
          </article>
        }
      </div>
      <rrhh-confirm-dialog />
    </div>
  `,
})
export class AppLayoutComponent {
  constructor(
    readonly auth: AuthService,
    readonly toast: ToastService,
  ) {}
}
