// src/app/features/catalogs/pages/catalog-management-page.tsx
import { useState, type FormEvent } from 'react';
import { useServices } from '../../../core/di/services-context';
import { useErrorToast } from '../../../core/services/use-error-toast';
import { useCatalogs } from '../use-catalogs';
import {
  CATALOG_FAMILY_LABELS,
  type CatalogFamily,
  type CatalogItem,
} from '../models/catalog.models';

const FAMILY_OPTIONS = (Object.keys(CATALOG_FAMILY_LABELS) as CatalogFamily[]).map((key) => ({
  key,
  label: CATALOG_FAMILY_LABELS[key],
}));

export function CatalogManagementPage() {
  const { toastService, confirmDialogService } = useServices();
  const notifyError = useErrorToast();
  const catalogService = useCatalogs();

  const [activeFamily, setActiveFamily] = useState<CatalogFamily>('language');
  const [newNameEs, setNewNameEs] = useState('');
  const [newCode, setNewCode] = useState('');
  const [editingId, setEditingId] = useState('');
  const [editNameEs, setEditNameEs] = useState('');
  const [editCode, setEditCode] = useState('');

  const items = catalogService.list(activeFamily, true);
  const activeCount = items.filter((item) => item.isActive).length;

  const cancelEdit = (): void => {
    setEditingId('');
    setEditNameEs('');
    setEditCode('');
  };

  const createItem = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    try {
      catalogService.create(activeFamily, newNameEs, newCode);
      setNewNameEs('');
      setNewCode('');
      toastService.show('Elemento creado.', 'success');
    } catch (error) {
      notifyError(error, 'No se pudo crear el elemento.');
    }
  };

  const startEdit = (item: CatalogItem): void => {
    setEditingId(item.id);
    setEditNameEs(item.nameEs);
    setEditCode(item.code);
  };

  const saveEdit = (item: CatalogItem): void => {
    try {
      catalogService.update(activeFamily, item.id, { nameEs: editNameEs, code: editCode });
      cancelEdit();
      toastService.show('Elemento actualizado.', 'success');
    } catch (error) {
      notifyError(error, 'No se pudo actualizar el elemento.');
    }
  };

  const toggle = (item: CatalogItem): void => {
    try {
      const updated = catalogService.toggleActive(activeFamily, item.id);
      toastService.show(
        updated.isActive ? 'Elemento activado.' : 'Elemento desactivado.',
        'success',
      );
    } catch (error) {
      notifyError(error, 'No se pudo actualizar el estado.');
    }
  };

  const remove = async (item: CatalogItem): Promise<void> => {
    const confirmDelete = await confirmDialogService.confirm({
      title: 'Eliminar valor de catálogo',
      message: `Se eliminará "${item.nameEs}" y no podrás recuperarlo automáticamente.`,
      confirmText: 'Eliminar',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmDelete) {
      return;
    }
    catalogService.remove(activeFamily, item.id);
    if (editingId === item.id) {
      cancelEdit();
    }
    toastService.show('Elemento eliminado.', 'success');
  };

  return (
    <section className="page">
      <div className="toolbar">
        <div className="page-header">
          <h1>Catálogos</h1>
          <p className="muted">
            Gestiona idiomas, programas, habilidades y listas maestras usadas por toda la app.
          </p>
        </div>
        <button
          className="button secondary"
          type="button"
          disabled={!editingId}
          onClick={cancelEdit}
        >
          Cancelar edición
        </button>
      </div>

      <div className="panel stack">
        <div className="toolbar">
          <div className="field field--wide">
            <label htmlFor="family">Familia de catálogo</label>
            <select
              id="family"
              name="family"
              value={activeFamily}
              onChange={(e) => {
                setActiveFamily(e.target.value as CatalogFamily);
                cancelEdit();
              }}
            >
              {FAMILY_OPTIONS.map((family) => (
                <option key={family.key} value={family.key}>
                  {family.label}
                </option>
              ))}
            </select>
          </div>
          <p className="muted">
            Activos: {activeCount} · Total: {items.length}
          </p>
        </div>

        {editingId ? (
          <p className="empty-state">
            Modo edición activo. Guarda cambios o cancela antes de cambiar de familia.
          </p>
        ) : null}

        <form className="grid two" onSubmit={createItem} noValidate>
          <div className="field">
            <label htmlFor="newNameEs">Nombre (es)</label>
            <input
              id="newNameEs"
              name="newNameEs"
              value={newNameEs}
              onChange={(e) => setNewNameEs(e.target.value)}
              required
            />
          </div>
          <div className="field">
            <label htmlFor="newCode">Código (opcional)</label>
            <input
              id="newCode"
              name="newCode"
              value={newCode}
              placeholder="Se autogenera si lo dejas vacio"
              onChange={(e) => setNewCode(e.target.value)}
            />
          </div>
          <div className="form-actions span-all">
            <button className="button" type="submit" disabled={!!editingId}>
              Añadir
            </button>
          </div>
        </form>

        {!items.length ? (
          <p className="empty-state">No hay elementos en este catálogo.</p>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Orden</th>
                  <th>Código</th>
                  <th>Nombre</th>
                  <th>Estado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {items.map((item) => (
                  <tr key={item.id}>
                    <td>{item.sortOrder}</td>
                    <td>{item.code}</td>
                    <td>
                      {editingId === item.id ? (
                        <div className="grid two">
                          <input
                            name="editNameEs"
                            value={editNameEs}
                            onChange={(e) => setEditNameEs(e.target.value)}
                            required
                          />
                          <input
                            name="editCode"
                            value={editCode}
                            onChange={(e) => setEditCode(e.target.value)}
                            required
                          />
                        </div>
                      ) : (
                        item.nameEs
                      )}
                    </td>
                    <td>
                      <span className="badge">{item.isActive ? 'Activo' : 'Inactivo'}</span>
                    </td>
                    <td>
                      <div className="form-actions">
                        <button
                          className="button ghost"
                          type="button"
                          onClick={() => catalogService.move(activeFamily, item.id, -1)}
                        >
                          Subir
                        </button>
                        <button
                          className="button ghost"
                          type="button"
                          onClick={() => catalogService.move(activeFamily, item.id, 1)}
                        >
                          Bajar
                        </button>
                        {editingId === item.id ? (
                          <button className="button" type="button" onClick={() => saveEdit(item)}>
                            Guardar
                          </button>
                        ) : (
                          <button
                            className="button secondary"
                            type="button"
                            onClick={() => startEdit(item)}
                          >
                            Editar
                          </button>
                        )}
                        <button
                          className="button secondary"
                          type="button"
                          onClick={() => toggle(item)}
                        >
                          {item.isActive ? 'Desactivar' : 'Activar'}
                        </button>
                        <button
                          className="button danger"
                          type="button"
                          onClick={() => remove(item)}
                        >
                          Eliminar
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}

// src/app/features/catalogs/pages/catalog-management-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ToastService } from '../../../core/services/toast.service';
import { CatalogService } from '../services/catalog.service';
import { CATALOG_FAMILY_LABELS, CatalogFamily, CatalogItem } from '../models/catalog.models';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-catalog-management-page',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="page">
      <div class="toolbar">
        <div class="page-header">
          <h1>Catálogos</h1>
          <p class="muted">
            Gestiona idiomas, programas, habilidades y listas maestras usadas por toda la app.
          </p>
        </div>
        <button
          class="button secondary"
          type="button"
          [disabled]="!editingId"
          (click)="cancelEdit()"
        >
          Cancelar edición
        </button>
      </div>

      <div class="panel stack">
        <div class="toolbar">
          <div class="field" style="min-width: 320px;">
            <label>Familia de catálogo</label>
            <select name="family" [(ngModel)]="activeFamily" (ngModelChange)="cancelEdit()">
              @for (family of familyOptions; track family.key) {
                <option [value]="family.key">{{ family.label }}</option>
              }
            </select>
          </div>
          <p class="muted">Activos: {{ activeCount }} · Total: {{ allCount }}</p>
        </div>

        @if (editingId) {
          <p class="empty-state">
            Modo edición activo. Guarda cambios o cancela antes de cambiar de familia.
          </p>
        }

        <form class="grid two" (ngSubmit)="createItem()">
          <div class="field">
            <label>Nombre (es)</label>
            <input name="newNameEs" [(ngModel)]="newNameEs" required />
          </div>
          <div class="field">
            <label>Código (opcional)</label>
            <input
              name="newCode"
              [(ngModel)]="newCode"
              placeholder="Se autogenera si lo dejas vacio"
            />
          </div>
          <div class="form-actions" style="grid-column: 1 / -1;">
            <button class="button" type="submit" [disabled]="!!editingId">Añadir</button>
          </div>
        </form>

        @if (!items.length) {
          <p class="empty-state">No hay elementos en este catálogo.</p>
        } @else {
          <div class="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Orden</th>
                  <th>Código</th>
                  <th>Nombre</th>
                  <th>Estado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                @for (item of items; track item.id) {
                  <tr>
                    <td>{{ item.sortOrder }}</td>
                    <td>{{ item.code }}</td>
                    <td>
                      @if (editingId === item.id) {
                        <div class="grid two">
                          <input name="editNameEs" [(ngModel)]="editNameEs" required />
                          <input name="editCode" [(ngModel)]="editCode" required />
                        </div>
                      } @else {
                        {{ item.nameEs }}
                      }
                    </td>
                    <td>
                      <span class="badge">{{ item.isActive ? 'Activo' : 'Inactivo' }}</span>
                    </td>
                    <td>
                      <div class="form-actions">
                        <button class="button ghost" type="button" (click)="move(item, -1)">
                          Subir
                        </button>
                        <button class="button ghost" type="button" (click)="move(item, 1)">
                          Bajar
                        </button>
                        @if (editingId === item.id) {
                          <button class="button" type="button" (click)="saveEdit(item)">
                            Guardar
                          </button>
                        } @else {
                          <button class="button secondary" type="button" (click)="startEdit(item)">
                            Editar
                          </button>
                        }
                        <button class="button secondary" type="button" (click)="toggle(item)">
                          {{ item.isActive ? 'Desactivar' : 'Activar' }}
                        </button>
                        <button class="button danger" type="button" (click)="remove(item)">
                          Eliminar
                        </button>
                      </div>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </div>
    </section>
  `,
})
export class CatalogManagementPageComponent {
  readonly familyOptions = (Object.keys(CATALOG_FAMILY_LABELS) as CatalogFamily[]).map((key) => ({
    key,
    label: CATALOG_FAMILY_LABELS[key],
  }));

  activeFamily: CatalogFamily = 'language';
  newNameEs = '';
  newCode = '';
  editingId = '';
  editNameEs = '';
  editCode = '';

  constructor(
    private readonly catalogService: CatalogService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  get items(): CatalogItem[] {
    return this.catalogService.list(this.activeFamily, true);
  }

  get activeCount(): number {
    return this.items.filter((item) => item.isActive).length;
  }

  get allCount(): number {
    return this.items.length;
  }

  createItem(): void {
    try {
      this.catalogService.create(this.activeFamily, this.newNameEs, this.newCode);
      this.newNameEs = '';
      this.newCode = '';
      this.toast.show('Elemento creado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo crear el elemento.',
        'error',
      );
    }
  }

  startEdit(item: CatalogItem): void {
    this.editingId = item.id;
    this.editNameEs = item.nameEs;
    this.editCode = item.code;
  }

  saveEdit(item: CatalogItem): void {
    try {
      this.catalogService.update(this.activeFamily, item.id, {
        nameEs: this.editNameEs,
        code: this.editCode,
      });
      this.cancelEdit();
      this.toast.show('Elemento actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el elemento.',
        'error',
      );
    }
  }

  cancelEdit(): void {
    this.editingId = '';
    this.editNameEs = '';
    this.editCode = '';
  }

  toggle(item: CatalogItem): void {
    try {
      const updated = this.catalogService.toggleActive(this.activeFamily, item.id);
      this.toast.show(updated.isActive ? 'Elemento activado.' : 'Elemento desactivado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el estado.',
        'error',
      );
    }
  }

  move(item: CatalogItem, direction: -1 | 1): void {
    this.catalogService.move(this.activeFamily, item.id, direction);
  }

  async remove(item: CatalogItem): Promise<void> {
    const confirmDelete = await this.confirmDialog.confirm({
      title: 'Eliminar valor de catálogo',
      message: `Se eliminará "${item.nameEs}" y no podrás recuperarlo automáticamente.`,
      confirmText: 'Eliminar',
      cancelText: 'Cancelar',
      danger: true,
    });

    if (!confirmDelete) {
      return;
    }

    this.catalogService.remove(this.activeFamily, item.id);
    if (this.editingId === item.id) {
      this.cancelEdit();
    }
    this.toast.show('Elemento eliminado.', 'success');
  }
}
