// frontend/src/app/features/catalogs/pages/catalog-management-page.tsx
import { useState, type FormEvent, type KeyboardEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { useServices } from '../../../core/di/services-context';
import { useErrorToast } from '../../../core/services/use-error-toast';
import { useCatalogs } from '../use-catalogs';
import {
  CATALOG_FAMILY_LABELS,
  type CatalogFamily,
  type CatalogItem,
} from '../models/catalog.models';

const FAMILY_OPTIONS = (Object.keys(CATALOG_FAMILY_LABELS) as CatalogFamily[]).map((key) => ({
  key,
  label: CATALOG_FAMILY_LABELS[key],
}));

export function CatalogManagementPage() {
  const { t } = useTranslation();
  const { toastService, confirmDialogService } = useServices();
  const notifyError = useErrorToast();
  const catalogService = useCatalogs();

  const [activeFamily, setActiveFamily] = useState<CatalogFamily>('language');
  const [newNameEs, setNewNameEs] = useState('');
  const [newCode, setNewCode] = useState('');
  const [editingId, setEditingId] = useState('');
  const [editNameEs, setEditNameEs] = useState('');
  const [editCode, setEditCode] = useState('');

  const items = catalogService.list(activeFamily, true);
  const activeCount = items.filter((item) => item.isActive).length;
  const isLoading = catalogService.status === 'idle' || catalogService.status === 'loading';
  const hasFailed = catalogService.status === 'error';

  const cancelEdit = (): void => {
    setEditingId('');
    setEditNameEs('');
    setEditCode('');
  };

  const createItem = async (event: FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault();
    try {
      await catalogService.create(activeFamily, newNameEs, newCode);
      setNewNameEs('');
      setNewCode('');
      toastService.show(t('catalogs.management.toast.created'), 'success');
    } catch (error) {
      notifyError(error, t('catalogs.management.error.create'));
    }
  };

  const startEdit = (item: CatalogItem): void => {
    setEditingId(item.id);
    setEditNameEs(item.nameEs);
    setEditCode(item.code);
  };

  const saveEdit = async (item: CatalogItem): Promise<void> => {
    try {
      await catalogService.update(activeFamily, item.id, { nameEs: editNameEs, code: editCode });
      cancelEdit();
      toastService.show(t('catalogs.management.toast.updated'), 'success');
    } catch (error) {
      notifyError(error, t('catalogs.management.error.update'));
    }
  };

  /** Enter saves and Escape cancels, as in any inline editor. */
  const onEditKeyDown = (event: KeyboardEvent<HTMLInputElement>, item: CatalogItem): void => {
    if (event.key === 'Enter') {
      event.preventDefault();
      void saveEdit(item);
    } else if (event.key === 'Escape') {
      event.preventDefault();
      cancelEdit();
    }
  };

  /**
   * Deactivation is the only way to retire a value: catalog values are never deleted,
   * so existing candidate records keep their meaning.
   */
  const toggle = async (item: CatalogItem): Promise<void> => {
    if (item.isActive) {
      const confirmDeactivate = await confirmDialogService.confirm({
        title: t('catalogs.management.confirmDeactivate.title'),
        message: t('catalogs.management.confirmDeactivate.message', { name: item.nameEs }),
        confirmText: t('catalogs.management.action.deactivate'),
        cancelText: t('catalogs.management.action.cancel'),
        danger: true,
      });
      if (!confirmDeactivate) {
        return;
      }
    }
    try {
      const updated = await catalogService.toggleActive(activeFamily, item.id);
      toastService.show(
        t(
          updated.isActive
            ? 'catalogs.management.toast.activated'
            : 'catalogs.management.toast.deactivated',
        ),
        'success',
      );
    } catch (error) {
      notifyError(error, t('catalogs.management.error.toggle'));
    }
  };

  const move = async (item: CatalogItem, direction: -1 | 1): Promise<void> => {
    try {
      await catalogService.move(activeFamily, item.id, direction);
    } catch (error) {
      notifyError(error, t('catalogs.management.error.move'));
    }
  };

  return (
    <section className="page">
      <div className="page-header">
        <h1>{t('catalogs.management.title')}</h1>
        <p className="muted">{t('catalogs.management.subtitle')}</p>
      </div>

      <div className="panel stack">
        <div className="toolbar">
          <div className="field field--wide">
            <label htmlFor="family">{t('catalogs.management.family')}</label>
            <select
              id="family"
              name="family"
              value={activeFamily}
              onChange={(e) => {
                setActiveFamily(e.target.value as CatalogFamily);
                cancelEdit();
              }}
            >
              {FAMILY_OPTIONS.map((family) => (
                <option key={family.key} value={family.key}>
                  {family.label}
                </option>
              ))}
            </select>
          </div>
          <p className="muted">
            {isLoading
              ? t('catalogs.management.loading')
              : hasFailed
                ? t('catalogs.management.loadFailed')
                : t('catalogs.management.counts', { active: activeCount, total: items.length })}
          </p>
        </div>

        <form className="grid two" onSubmit={(event) => void createItem(event)} noValidate>
          <div className="field">
            <label htmlFor="newNameEs">{t('catalogs.management.form.name')}</label>
            <input
              id="newNameEs"
              name="newNameEs"
              value={newNameEs}
              onChange={(e) => setNewNameEs(e.target.value)}
              required
            />
          </div>
          <div className="field">
            <label htmlFor="newCode">{t('catalogs.management.form.code')}</label>
            <input
              id="newCode"
              name="newCode"
              value={newCode}
              placeholder={t('catalogs.management.form.codePlaceholder')}
              onChange={(e) => setNewCode(e.target.value)}
            />
          </div>
          <div className="form-actions span-all">
            <button
              className="button"
              type="submit"
              disabled={!!editingId || isLoading || hasFailed}
            >
              {t('catalogs.management.form.add')}
            </button>
          </div>
        </form>

        {isLoading ? (
          <p className="empty-state">{t('catalogs.management.loading')}</p>
        ) : hasFailed ? (
          <p className="empty-state">
            {catalogService.error?.message ?? t('catalogs.management.loadFailed')}
          </p>
        ) : !items.length ? (
          <p className="empty-state">{t('catalogs.management.empty')}</p>
        ) : (
          <div className="table-wrap">
            <table className="catalog-table">
              <thead>
                <tr>
                  <th>{t('catalogs.management.column.order')}</th>
                  <th>{t('catalogs.management.column.code')}</th>
                  <th>{t('catalogs.management.column.name')}</th>
                  <th>{t('catalogs.management.column.status')}</th>
                  <th>{t('catalogs.management.column.actions')}</th>
                </tr>
              </thead>
              <tbody>
                {items.map((item) => {
                  const isEditing = editingId === item.id;
                  // While one row is edited, the other rows' actions are disabled
                  // (not hidden, so the table does not reflow) until Save or Cancel.
                  const isLocked = !!editingId && !isEditing;
                  return (
                    <tr key={item.id} className={isEditing ? 'is-editing' : undefined}>
                      <td>{item.sortOrder}</td>
                      <td>
                        {isEditing ? (
                          <input
                            className="cell-input"
                            name="editCode"
                            aria-label={t('catalogs.management.edit.code', {
                              name: item.nameEs,
                            })}
                            value={editCode}
                            onChange={(e) => setEditCode(e.target.value)}
                            onKeyDown={(e) => onEditKeyDown(e, item)}
                            required
                          />
                        ) : (
                          item.code
                        )}
                      </td>
                      <td>
                        {isEditing ? (
                          <input
                            className="cell-input"
                            name="editNameEs"
                            aria-label={t('catalogs.management.edit.name', {
                              name: item.nameEs,
                            })}
                            value={editNameEs}
                            onChange={(e) => setEditNameEs(e.target.value)}
                            onKeyDown={(e) => onEditKeyDown(e, item)}
                            autoFocus
                            required
                          />
                        ) : (
                          item.nameEs
                        )}
                      </td>
                      <td>
                        <span className="badge">
                          {t(
                            item.isActive
                              ? 'catalogs.management.status.active'
                              : 'catalogs.management.status.inactive',
                          )}
                        </span>
                      </td>
                      <td>
                        <div className="form-actions">
                          {isEditing ? (
                            <>
                              <button
                                className="button"
                                type="button"
                                data-testid="catalog-edit-save"
                                onClick={() => void saveEdit(item)}
                              >
                                {t('catalogs.management.action.save')}
                              </button>
                              <button
                                className="button ghost"
                                type="button"
                                data-testid="catalog-edit-cancel"
                                onClick={cancelEdit}
                              >
                                {t('catalogs.management.action.cancel')}
                              </button>
                            </>
                          ) : (
                            <>
                              <button
                                className="button ghost"
                                type="button"
                                disabled={isLocked}
                                onClick={() => void move(item, -1)}
                              >
                                {t('catalogs.management.action.moveUp')}
                              </button>
                              <button
                                className="button ghost"
                                type="button"
                                disabled={isLocked}
                                onClick={() => void move(item, 1)}
                              >
                                {t('catalogs.management.action.moveDown')}
                              </button>
                              <button
                                className="button secondary"
                                type="button"
                                data-testid="catalog-edit"
                                disabled={isLocked}
                                onClick={() => startEdit(item)}
                              >
                                {t('catalogs.management.action.edit')}
                              </button>
                              <button
                                className={item.isActive ? 'button danger' : 'button secondary'}
                                type="button"
                                disabled={isLocked}
                                onClick={() => void toggle(item)}
                              >
                                {t(
                                  item.isActive
                                    ? 'catalogs.management.action.deactivate'
                                    : 'catalogs.management.action.activate',
                                )}
                              </button>
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}

// src/app/features/catalogs/pages/catalog-management-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ToastService } from '../../../core/services/toast.service';
import { CatalogService } from '../services/catalog.service';
import { CATALOG_FAMILY_LABELS, CatalogFamily, CatalogItem } from '../models/catalog.models';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-catalog-management-page',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="page">
      <div class="toolbar">
        <div class="page-header">
          <h1>Catalogos</h1>
          <p class="muted">
            Gestiona idiomas, programas, habilidades y listas maestras usadas por toda la app.
          </p>
        </div>
        <button
          class="button secondary"
          type="button"
          [disabled]="!editingId"
          (click)="cancelEdit()"
        >
          Cancelar edicion
        </button>
      </div>

      <div class="panel stack">
        <div class="toolbar">
          <div class="field" style="min-width: 320px;">
            <label>Familia de catalogo</label>
            <select name="family" [(ngModel)]="activeFamily" (ngModelChange)="cancelEdit()">
              @for (family of familyOptions; track family.key) {
                <option [value]="family.key">{{ family.label }}</option>
              }
            </select>
          </div>
          <p class="muted">Activos: {{ activeCount }} · Total: {{ allCount }}</p>
        </div>

        @if (editingId) {
          <p class="empty-state">
            Modo edicion activo. Guarda cambios o cancela antes de cambiar de familia.
          </p>
        }

        <form class="grid two" (ngSubmit)="createItem()">
          <div class="field">
            <label>Nombre (es)</label>
            <input name="newNameEs" [(ngModel)]="newNameEs" required />
          </div>
          <div class="field">
            <label>Codigo (opcional)</label>
            <input
              name="newCode"
              [(ngModel)]="newCode"
              placeholder="Se autogenera si lo dejas vacio"
            />
          </div>
          <div class="form-actions" style="grid-column: 1 / -1;">
            <button class="button" type="submit" [disabled]="!!editingId">Anadir</button>
          </div>
        </form>

        @if (!items.length) {
          <p class="empty-state">No hay elementos en este catalogo.</p>
        } @else {
          <div class="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Orden</th>
                  <th>Codigo</th>
                  <th>Nombre</th>
                  <th>Estado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                @for (item of items; track item.id) {
                  <tr>
                    <td>{{ item.sortOrder }}</td>
                    <td>{{ item.code }}</td>
                    <td>
                      @if (editingId === item.id) {
                        <div class="grid two">
                          <input name="editNameEs" [(ngModel)]="editNameEs" required />
                          <input name="editCode" [(ngModel)]="editCode" required />
                        </div>
                      } @else {
                        {{ item.nameEs }}
                      }
                    </td>
                    <td>
                      <span class="badge">{{ item.isActive ? 'Activo' : 'Inactivo' }}</span>
                    </td>
                    <td>
                      <div class="form-actions">
                        <button class="button ghost" type="button" (click)="move(item, -1)">
                          Subir
                        </button>
                        <button class="button ghost" type="button" (click)="move(item, 1)">
                          Bajar
                        </button>
                        @if (editingId === item.id) {
                          <button class="button" type="button" (click)="saveEdit(item)">
                            Guardar
                          </button>
                        } @else {
                          <button class="button secondary" type="button" (click)="startEdit(item)">
                            Editar
                          </button>
                        }
                        <button class="button secondary" type="button" (click)="toggle(item)">
                          {{ item.isActive ? 'Desactivar' : 'Activar' }}
                        </button>
                        <button class="button danger" type="button" (click)="remove(item)">
                          Eliminar
                        </button>
                      </div>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      </div>
    </section>
  `,
})
export class CatalogManagementPageComponent {
  readonly familyOptions = (Object.keys(CATALOG_FAMILY_LABELS) as CatalogFamily[]).map((key) => ({
    key,
    label: CATALOG_FAMILY_LABELS[key],
  }));

  activeFamily: CatalogFamily = 'language';
  newNameEs = '';
  newCode = '';
  editingId = '';
  editNameEs = '';
  editCode = '';

  constructor(
    private readonly catalogService: CatalogService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  get items(): CatalogItem[] {
    return this.catalogService.list(this.activeFamily, true);
  }

  get activeCount(): number {
    return this.items.filter((item) => item.isActive).length;
  }

  get allCount(): number {
    return this.items.length;
  }

  createItem(): void {
    try {
      this.catalogService.create(this.activeFamily, this.newNameEs, this.newCode);
      this.newNameEs = '';
      this.newCode = '';
      this.toast.show('Elemento creado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo crear el elemento.',
        'error',
      );
    }
  }

  startEdit(item: CatalogItem): void {
    this.editingId = item.id;
    this.editNameEs = item.nameEs;
    this.editCode = item.code;
  }

  saveEdit(item: CatalogItem): void {
    try {
      this.catalogService.update(this.activeFamily, item.id, {
        nameEs: this.editNameEs,
        code: this.editCode,
      });
      this.cancelEdit();
      this.toast.show('Elemento actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el elemento.',
        'error',
      );
    }
  }

  cancelEdit(): void {
    this.editingId = '';
    this.editNameEs = '';
    this.editCode = '';
  }

  toggle(item: CatalogItem): void {
    try {
      const updated = this.catalogService.toggleActive(this.activeFamily, item.id);
      this.toast.show(updated.isActive ? 'Elemento activado.' : 'Elemento desactivado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el estado.',
        'error',
      );
    }
  }

  move(item: CatalogItem, direction: -1 | 1): void {
    this.catalogService.move(this.activeFamily, item.id, direction);
  }

  async remove(item: CatalogItem): Promise<void> {
    const confirmDelete = await this.confirmDialog.confirm({
      title: 'Eliminar valor de catalogo',
      message: `Se eliminara "${item.nameEs}" y no podras recuperarlo automaticamente.`,
      confirmText: 'Eliminar',
      cancelText: 'Cancelar',
      danger: true,
    });

    if (!confirmDelete) {
      return;
    }

    this.catalogService.remove(this.activeFamily, item.id);
    if (this.editingId === item.id) {
      this.cancelEdit();
    }
    this.toast.show('Elemento eliminado.', 'success');
  }
}
