// src/app/features/admin/roles/admin-roles-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ToastService } from '../../../core/services/toast.service';
import { Permission, RoleDefinition } from '../../../shared/models/auth.models';
import { ProfileService } from '../users/profile.service';
import { RoleService } from './role.service';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-admin-roles-page',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="page">
      <div class="page-header">
        <h1>Roles</h1>
        <p class="muted">Gestiona roles y permisos funcionales para operar la aplicación.</p>
      </div>

      <form class="panel grid two" (ngSubmit)="createRole()">
        <div class="field">
          <label>Nombre interno</label>
          <input
            name="name"
            [(ngModel)]="newRoleName"
            placeholder="ej: recruiter_junior"
            required
          />
        </div>
        <div class="field">
          <label>Etiqueta visible</label>
          <input
            name="label"
            [(ngModel)]="newRoleLabel"
            placeholder="ej: Recruiter Junior"
            required
          />
        </div>
        <div class="form-actions" style="grid-column: 1 / -1;">
          <button class="button" type="submit">Crear rol</button>
        </div>
      </form>

      <div class="grid two">
        @for (role of roles.roles(); track role.name) {
          <article class="panel stack">
            <div class="toolbar">
              @if (editingRole === role.name) {
                <input name="editLabel" [(ngModel)]="editLabel" />
                <button class="button" type="button" (click)="saveLabel(role)">Guardar</button>
              } @else {
                <h2>{{ role.label }}</h2>
                <button class="button secondary" type="button" (click)="startEditLabel(role)">
                  Editar nombre
                </button>
              }
            </div>
            <p class="muted">
              {{ role.name }} · {{ role.isSystem ? 'Rol de sistema' : 'Rol personalizado' }}
            </p>
            <div class="grid">
              @for (permission of roles.allPermissions; track permission) {
                <label class="inline-check">
                  <input
                    type="checkbox"
                    [checked]="hasPermission(role, permission)"
                    (change)="togglePermission(role, permission, $any($event.target).checked)"
                  />
                  {{ permission }}
                </label>
              }
            </div>
            <div class="form-actions">
              <button
                class="button danger"
                type="button"
                [disabled]="role.isSystem || isRoleInUse(role.name)"
                (click)="remove(role)"
              >
                Eliminar rol
              </button>
            </div>
          </article>
        }
      </div>
    </section>
  `,
})
export class AdminRolesPageComponent {
  newRoleName = '';
  newRoleLabel = '';
  editingRole = '';
  editLabel = '';

  constructor(
    readonly roles: RoleService,
    private readonly users: ProfileService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  createRole(): void {
    try {
      this.roles.create(this.newRoleName, this.newRoleLabel);
      this.newRoleName = '';
      this.newRoleLabel = '';
      this.toast.show('Rol creado.', 'success');
    } catch (error) {
      this.toast.show(error instanceof Error ? error.message : 'No se pudo crear el rol.', 'error');
    }
  }

  startEditLabel(role: RoleDefinition): void {
    this.editingRole = role.name;
    this.editLabel = role.label;
  }

  saveLabel(role: RoleDefinition): void {
    try {
      this.roles.updateLabel(role.name, this.editLabel);
      this.editingRole = '';
      this.editLabel = '';
      this.toast.show('Rol actualizado.', 'success');
    } catch (error) {
      this.toast.show(error instanceof Error ? error.message : 'No se pudo actualizar.', 'error');
    }
  }

  hasPermission(role: RoleDefinition, permission: Permission): boolean {
    return role.permissions.includes(permission);
  }

  togglePermission(role: RoleDefinition, permission: Permission, enabled: boolean): void {
    try {
      this.roles.setPermission(role.name, permission, enabled);
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar permisos.',
        'error',
      );
    }
  }

  isRoleInUse(roleName: string): boolean {
    return this.users.users().some((user) => user.role === roleName);
  }

  async remove(role: RoleDefinition): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Eliminar rol',
      message: `Se eliminará el rol "${role.label}".`,
      confirmText: 'Eliminar rol',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }

    try {
      this.roles.remove(role.name);
      this.toast.show('Rol eliminado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo eliminar el rol.',
        'error',
      );
    }
  }
}

// src/app/features/admin/roles/admin-roles-page.tsx
import { useState, type FormEvent } from 'react';
import { useServices } from '../../../core/di/services-context';
import { useErrorToast } from '../../../core/services/use-error-toast';
import { useSignal } from '../../../core/state/use-signal';
import type { Permission, RoleDefinition } from '../../../shared/models/auth.models';

export function AdminRolesPage() {
  const { roleService, profileService, toastService, confirmDialogService } = useServices();
  const notify = useErrorToast();
  const roles = useSignal(roleService.roles);
  const users = useSignal(profileService.users);

  const [newRoleName, setNewRoleName] = useState('');
  const [newRoleLabel, setNewRoleLabel] = useState('');
  const [editingRole, setEditingRole] = useState('');
  const [editLabel, setEditLabel] = useState('');

  const createRole = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    try {
      roleService.create(newRoleName, newRoleLabel);
      setNewRoleName('');
      setNewRoleLabel('');
      toastService.show('Rol creado.', 'success');
    } catch (error) {
      notify(error, 'No se pudo crear el rol.');
    }
  };

  const saveLabel = (role: RoleDefinition): void => {
    try {
      roleService.updateLabel(role.name, editLabel);
      setEditingRole('');
      setEditLabel('');
      toastService.show('Rol actualizado.', 'success');
    } catch (error) {
      notify(error, 'No se pudo actualizar.');
    }
  };

  const togglePermission = (
    role: RoleDefinition,
    permission: Permission,
    enabled: boolean,
  ): void => {
    try {
      roleService.setPermission(role.name, permission, enabled);
    } catch (error) {
      notify(error, 'No se pudo actualizar permisos.');
    }
  };

  const remove = async (role: RoleDefinition): Promise<void> => {
    const confirmed = await confirmDialogService.confirm({
      title: 'Eliminar rol',
      message: `Se eliminará el rol "${role.label}".`,
      confirmText: 'Eliminar rol',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }
    try {
      roleService.remove(role.name);
      toastService.show('Rol eliminado.', 'success');
    } catch (error) {
      notify(error, 'No se pudo eliminar el rol.');
    }
  };

  const isRoleInUse = (roleName: string): boolean => users.some((user) => user.role === roleName);

  return (
    <section className="page">
      <div className="page-header">
        <h1>Roles</h1>
        <p className="muted">Gestiona roles y permisos funcionales para operar la aplicación.</p>
      </div>

      <form className="panel grid two" onSubmit={createRole} noValidate>
        <div className="field">
          <label htmlFor="role-name">Nombre interno</label>
          <input
            id="role-name"
            name="name"
            value={newRoleName}
            placeholder="ej: recruiter_junior"
            onChange={(e) => setNewRoleName(e.target.value)}
            required
          />
        </div>
        <div className="field">
          <label htmlFor="role-label">Etiqueta visible</label>
          <input
            id="role-label"
            name="label"
            value={newRoleLabel}
            placeholder="ej: Recruiter Junior"
            onChange={(e) => setNewRoleLabel(e.target.value)}
            required
          />
        </div>
        <div className="form-actions span-all">
          <button className="button" type="submit">
            Crear rol
          </button>
        </div>
      </form>

      <div className="grid two">
        {roles.map((role) => (
          <article className="panel stack" key={role.name}>
            <div className="toolbar">
              {editingRole === role.name ? (
                <>
                  <input
                    name="editLabel"
                    value={editLabel}
                    onChange={(e) => setEditLabel(e.target.value)}
                  />
                  <button className="button" type="button" onClick={() => saveLabel(role)}>
                    Guardar
                  </button>
                </>
              ) : (
                <>
                  <h2>{role.label}</h2>
                  <button
                    className="button secondary"
                    type="button"
                    onClick={() => {
                      setEditingRole(role.name);
                      setEditLabel(role.label);
                    }}
                  >
                    Editar nombre
                  </button>
                </>
              )}
            </div>
            <p className="muted">
              {role.name} · {role.isSystem ? 'Rol de sistema' : 'Rol personalizado'}
            </p>
            <div className="grid">
              {roleService.allPermissions.map((permission) => (
                <label className="inline-check" key={permission}>
                  <input
                    type="checkbox"
                    checked={role.permissions.includes(permission)}
                    onChange={(e) => togglePermission(role, permission, e.target.checked)}
                  />
                  {permission}
                </label>
              ))}
            </div>
            <div className="form-actions">
              <button
                className="button danger"
                type="button"
                disabled={role.isSystem || isRoleInUse(role.name)}
                onClick={() => remove(role)}
              >
                Eliminar rol
              </button>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
