// src/app/features/candidates/components/candidate-skills.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CatalogService } from '../../catalogs/services/catalog.service';
import { CandidateSkill } from '../models/candidate.models';
import { CandidateRelationsService } from '../services/candidate-relations.service';

@Component({
  selector: 'rrhh-candidate-skills',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="section-block">
      <h3 class="section-title">Habilidades</h3>
      @if (!skills.length) {
        <p class="empty-state">Sin habilidades registradas.</p>
      }
      <div class="item-list">
        @for (item of skills; track item.id) {
          <div class="item-row">
            <p class="item-main">
              <span class="badge">{{ item.skill }}</span> {{ item.level }}
            </p>
            @if (canEdit) {
              <button class="button secondary" type="button" (click)="remove(item.id)">
                Quitar
              </button>
            }
          </div>
        }
      </div>
      @if (canEdit) {
        <form class="section-block" (ngSubmit)="add()">
          <div class="grid two">
            <div class="field">
              <label>Habilidad</label>
              <select name="skill" [(ngModel)]="draft.skill" required>
                <option value="" disabled>Selecciona</option>
                @for (option of skillOptions; track option) {
                  <option [value]="option">{{ option }}</option>
                }
              </select>
            </div>
            <div class="field">
              <label>Nivel</label>
              <select name="level" [(ngModel)]="draft.level" required>
                <option value="" disabled>Selecciona</option>
                @for (option of levelOptions; track option) {
                  <option [value]="option">{{ option }}</option>
                }
              </select>
            </div>
          </div>
          @if (error) {
            <p class="empty-state">{{ error }}</p>
          }
          <div class="form-actions">
            <button class="button" type="submit">Anadir habilidad</button>
          </div>
        </form>
      }
    </section>
  `,
})
export class CandidateSkillsComponent {
  @Input() candidateId = '';
  @Input() skills: CandidateSkill[] = [];
  @Input() canEdit = false;

  draft = { skill: '', level: '' };
  error = '';

  constructor(
    private readonly relations: CandidateRelationsService,
    private readonly catalogs: CatalogService,
  ) {}

  get skillOptions(): string[] {
    return this.catalogs.activeNames('skill');
  }

  get levelOptions(): string[] {
    return this.catalogs.activeNames('skill_level');
  }

  add(): void {
    try {
      this.relations.addSkill(this.candidateId, { ...this.draft });
      this.draft = { skill: '', level: '' };
      this.error = '';
    } catch (err) {
      this.error = (err as Error).message;
    }
  }

  remove(skillId: string): void {
    this.relations.removeSkill(this.candidateId, skillId);
  }
}

// frontend/src/app/features/candidates/components/candidate-skills.tsx
import { useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { usePermission, useServices } from '../../../core/di/services-context';
import { errorText } from '../../../core/i18n/translatable-error';
import { useCatalogs } from '../../catalogs/use-catalogs';
import { CatalogStatusNotice } from '../../catalogs/components/catalog-status';
import { useCatalogStatus } from '../../catalogs/components/use-catalog-status';
import type { CandidateSkill } from '../models/candidate.models';

const EMPTY = { skill: '', level: '' };

interface Props {
  candidateId: string;
  skills: CandidateSkill[];
  /** See candidate-languages. */
  readOnly?: boolean;
}

export function CandidateSkills({ candidateId, skills, readOnly = false }: Props) {
  const { t } = useTranslation();
  const canUpdate = usePermission('candidates.update');
  const canEdit = !readOnly && canUpdate;
  const { candidateRelationsService } = useServices();
  const catalogs = useCatalogs();
  const [draft, setDraft] = useState(EMPTY);
  const [error, setError] = useState('');

  const catalogStatus = useCatalogStatus();
  const skillOptions = catalogs.activeNames('skill');
  const levelOptions = catalogs.activeNames('skill_level');

  // See candidate-languages: these persist through the API and must be awaited.
  const add = async (event: FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault();
    try {
      await candidateRelationsService.addSkill(candidateId, { ...draft });
      setDraft(EMPTY);
      setError('');
    } catch (err) {
      setError(errorText(err, t));
    }
  };

  const remove = async (skillId: string): Promise<void> => {
    try {
      await candidateRelationsService.removeSkill(candidateId, skillId);
      setError('');
    } catch (err) {
      setError(errorText(err, t));
    }
  };

  return (
    <section className="section-block" data-testid="candidate-skills">
      <h3 className="section-title">{t('candidate.profile.skills.title')}</h3>
      {!skills.length ? <p className="empty-state">{t('candidate.profile.skills.empty')}</p> : null}
      <div className="item-list">
        {skills.map((item) => (
          <div className="item-row" key={item.id}>
            <p className="item-main">
              <span className="badge">{item.skill}</span> {item.level}
            </p>
            {canEdit ? (
              <button
                className="button secondary"
                type="button"
                onClick={() => void remove(item.id)}
              >
                {t('candidate.profile.action.remove')}
              </button>
            ) : null}
          </div>
        ))}
      </div>
      {canEdit ? (
        <form className="section-block" onSubmit={add} noValidate>
          <CatalogStatusNotice status={catalogStatus} />
          <div className="grid two">
            <div className="field">
              <label htmlFor="skill">{t('candidate.profile.skills.label')}</label>
              <select
                id="skill"
                name="skill"
                value={draft.skill}
                onChange={(e) => setDraft({ ...draft, skill: e.target.value })}
                required
              >
                <option value="" disabled>
                  {t('candidate.profile.option.select')}
                </option>
                {skillOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="skill-level">{t('candidate.profile.skills.level')}</label>
              <select
                id="skill-level"
                name="level"
                value={draft.level}
                onChange={(e) => setDraft({ ...draft, level: e.target.value })}
                required
              >
                <option value="" disabled>
                  {t('candidate.profile.option.select')}
                </option>
                {levelOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
          </div>
          {error ? <p className="empty-state">{error}</p> : null}
          <div className="form-actions">
            <button className="button" type="submit" disabled={!!catalogStatus.message}>
              {t('candidate.profile.skills.add')}
            </button>
          </div>
        </form>
      ) : null}
    </section>
  );
}
