// src/app/features/candidates/pages/candidate-edit-page.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { CandidateFormComponent } from '../components/candidate-form.component';
import { CandidateDraft } from '../models/candidate.models';
import { CandidateService } from '../services/candidate.service';

@Component({
  selector: 'rrhh-candidate-edit-page',
  standalone: true,
  imports: [CandidateFormComponent],
  template: `
    <section class="page">
      <div class="page-header">
        <h1>{{ candidateId ? 'Editar candidato' : 'Alta de candidato' }}</h1>
        <p class="muted">Los cambios quedan preparados para auditoría y RLS.</p>
      </div>
      <div class="panel">
        <rrhh-candidate-form [candidate]="candidate" (save)="save($event)" />
      </div>
    </section>
  `,
})
export class CandidateEditPageComponent {
  @Input('id') candidateId = '';

  constructor(
    private readonly candidateService: CandidateService,
    private readonly router: Router,
  ) {}

  get candidate() {
    return this.candidateId ? this.candidateService.find(this.candidateId) : undefined;
  }

  async save(draft: CandidateDraft): Promise<void> {
    const candidate = this.candidateId
      ? this.candidateService.update(this.candidateId, draft)
      : this.candidateService.create(draft);
    await this.router.navigate(['/app/candidates', candidate.id]);
  }
}

// src/app/features/candidates/pages/candidate-edit-page.tsx
import { useNavigate, useParams } from 'react-router';
import { useCandidates } from '../use-candidates';
import { CandidateForm } from '../components/candidate-form';
import type { CandidateDraft } from '../models/candidate.models';

export function CandidateEditPage() {
  // The '' default reproduces Angular's @Input('id') default on /candidates/new,
  // which is what selects the heading below.
  const { id: candidateId = '' } = useParams<{ id: string }>();
  const candidateService = useCandidates();
  const navigate = useNavigate();

  const candidate = candidateId ? candidateService.find(candidateId) : undefined;

  const save = async (draft: CandidateDraft): Promise<void> => {
    const saved = candidateId
      ? candidateService.update(candidateId, draft)
      : candidateService.create(draft);
    await navigate(`/app/candidates/${saved.id}`);
  };

  return (
    <section className="page">
      <div className="page-header">
        <h1>{candidateId ? 'Editar candidato' : 'Alta de candidato'}</h1>
        <p className="muted">Los cambios quedan preparados para auditoría y RLS.</p>
      </div>
      <div className="panel">
        {/* key remounts the form when navigating between new and edit. */}
        <CandidateForm key={candidateId || 'new'} candidate={candidate} onSave={save} />
      </div>
    </section>
  );
}
