// src/app/features/candidates/pages/candidate-detail-page.tsx
import { Link, useParams } from 'react-router';
import { usePermission, useServices } from '../../../core/di/services-context';
import { useCandidates } from '../use-candidates';
import { CandidateDocuments } from '../components/candidate-documents';
import { CandidateEducation } from '../components/candidate-education';
import { CandidateExperience } from '../components/candidate-experience';
import { CandidateLanguages } from '../components/candidate-languages';
import { CandidatePrograms } from '../components/candidate-programs';
import { CandidateSkills } from '../components/candidate-skills';

export function CandidateDetailPage() {
  const { id: candidateId = '' } = useParams<{ id: string }>();
  const { confirmDialogService } = useServices();
  const candidateService = useCandidates();

  const item = candidateService.find(candidateId);
  const canEdit = usePermission('edit_candidates');

  const setActive = async (active: boolean): Promise<void> => {
    if (!item) {
      return;
    }
    const confirmed = await confirmDialogService.confirm({
      title: active ? 'Aplicar alta lógica' : 'Aplicar baja lógica',
      message: active
        ? 'El candidato volverá a aparecer en listados activos.'
        : 'El candidato dejará de aparecer en listados activos.',
      confirmText: active ? 'Aplicar alta' : 'Aplicar baja',
      cancelText: 'Cancelar',
      danger: !active,
    });
    if (!confirmed) {
      return;
    }
    if (active) {
      candidateService.reactivate(item.id);
    } else {
      candidateService.deactivate(item.id);
    }
  };

  if (!item) {
    return (
      <section className="panel">
        <h1>Candidato no encontrado</h1>
        <Link className="button" to="/app/candidates">
          Volver
        </Link>
      </section>
    );
  }

  return (
    <section className="page">
      <div className="toolbar">
        <div className="page-header">
          <h1>
            {item.firstName} {item.lastName}
          </h1>
          <p className="muted">
            {item.email} · {item.phone}
          </p>
        </div>
        <div className="toolbar">
          {canEdit ? (
            <>
              <Link className="button secondary" to={`/app/candidates/${item.id}/edit`}>
                Editar
              </Link>
              {item.isActive ? (
                <button className="button danger" type="button" onClick={() => setActive(false)}>
                  Baja lógica
                </button>
              ) : (
                <button className="button secondary" type="button" onClick={() => setActive(true)}>
                  Alta lógica
                </button>
              )}
            </>
          ) : null}
        </div>
      </div>
      <div className="grid two">
        <article className="panel">
          <h2>Datos principales</h2>
          <p>
            <strong>Estado:</strong> {item.status}
          </p>
          <p>
            <strong>Disponibilidad:</strong> {item.availability}
          </p>
          <p>
            <strong>Localidad:</strong> {item.location} {item.province}
          </p>
          <p>
            <strong>Recepción:</strong> {item.receivedAt || 'Pendiente'}
          </p>
          <p>
            <strong>Revisión:</strong> {item.reviewDueAt || 'Pendiente'}
          </p>
          <p>{item.notes}</p>
        </article>
        <article className="panel">
          <h2>Auditoría</h2>
          <p>
            <strong>Creado:</strong> {item.createdAt.slice(0, 19)}
          </p>
          <p>
            <strong>Actualizado:</strong> {item.updatedAt.slice(0, 19)}
          </p>
          <p>
            <strong>Activo:</strong> {item.isActive ? 'Si' : 'No'}
          </p>
        </article>
      </div>
      <div className="grid two">
        <article className="panel">
          <CandidateLanguages candidateId={item.id} languages={item.languages} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidatePrograms candidateId={item.id} programs={item.programs} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateEducation candidateId={item.id} education={item.education} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateExperience
            candidateId={item.id}
            experience={item.experience}
            canEdit={canEdit}
          />
        </article>
        <article className="panel">
          <CandidateSkills candidateId={item.id} skills={item.skills} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateDocuments candidate={item} />
        </article>
      </div>
    </section>
  );
}

// src/app/features/candidates/pages/candidate-detail-page.component.ts
import { Component, Input } from '@angular/core';
import { SlicePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../../core/auth/auth.service';
import { CandidateDocumentsComponent } from '../components/candidate-documents.component';
import { CandidateEducationComponent } from '../components/candidate-education.component';
import { CandidateExperienceComponent } from '../components/candidate-experience.component';
import { CandidateLanguagesComponent } from '../components/candidate-languages.component';
import { CandidateProgramsComponent } from '../components/candidate-programs.component';
import { CandidateSkillsComponent } from '../components/candidate-skills.component';
import { CandidateService } from '../services/candidate.service';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-candidate-detail-page',
  standalone: true,
  imports: [
    RouterLink,
    SlicePipe,
    CandidateLanguagesComponent,
    CandidateProgramsComponent,
    CandidateEducationComponent,
    CandidateExperienceComponent,
    CandidateSkillsComponent,
    CandidateDocumentsComponent,
  ],
  template: `
    @if (candidate; as item) {
      <section class="page">
        <div class="toolbar">
          <div class="page-header">
            <h1>{{ item.firstName }} {{ item.lastName }}</h1>
            <p class="muted">{{ item.email }} · {{ item.phone }}</p>
          </div>
          <div class="toolbar">
            @if (auth.hasPermission('edit_candidates')) {
              <a class="button secondary" [routerLink]="['/app/candidates', item.id, 'edit']"
                >Editar</a
              >
              @if (item.isActive) {
                <button class="button danger" type="button" (click)="deactivate(item.id)">
                  Baja lógica
                </button>
              } @else {
                <button class="button secondary" type="button" (click)="reactivate(item.id)">
                  Alta lógica
                </button>
              }
            }
          </div>
        </div>
        <div class="grid two">
          <article class="panel">
            <h2>Datos principales</h2>
            <p><strong>Estado:</strong> {{ item.status }}</p>
            <p><strong>Disponibilidad:</strong> {{ item.availability }}</p>
            <p><strong>Localidad:</strong> {{ item.location }} {{ item.province }}</p>
            <p><strong>Recepción:</strong> {{ item.receivedAt || 'Pendiente' }}</p>
            <p><strong>Revisión:</strong> {{ item.reviewDueAt || 'Pendiente' }}</p>
            <p>{{ item.notes }}</p>
          </article>
          <article class="panel">
            <h2>Auditoría</h2>
            <p><strong>Creado:</strong> {{ item.createdAt | slice: 0 : 19 }}</p>
            <p><strong>Actualizado:</strong> {{ item.updatedAt | slice: 0 : 19 }}</p>
            <p><strong>Activo:</strong> {{ item.isActive ? 'Si' : 'No' }}</p>
          </article>
        </div>
        <div class="grid two">
          <article class="panel">
            <rrhh-candidate-languages
              [candidateId]="item.id"
              [languages]="item.languages"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-programs
              [candidateId]="item.id"
              [programs]="item.programs"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-education
              [candidateId]="item.id"
              [education]="item.education"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-experience
              [candidateId]="item.id"
              [experience]="item.experience"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-skills
              [candidateId]="item.id"
              [skills]="item.skills"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel"><rrhh-candidate-documents [candidate]="item" /></article>
        </div>
      </section>
    } @else {
      <section class="panel">
        <h1>Candidato no encontrado</h1>
        <a class="button" routerLink="/app/candidates">Volver</a>
      </section>
    }
  `,
})
export class CandidateDetailPageComponent {
  @Input('id') candidateId = '';

  constructor(
    readonly auth: AuthService,
    private readonly candidateService: CandidateService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  get candidate() {
    return this.candidateService.find(this.candidateId);
  }

  async deactivate(id: string): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Aplicar baja lógica',
      message: 'El candidato dejará de aparecer en listados activos.',
      confirmText: 'Aplicar baja',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }
    this.candidateService.deactivate(id);
  }

  async reactivate(id: string): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Aplicar alta lógica',
      message: 'El candidato volverá a aparecer en listados activos.',
      confirmText: 'Aplicar alta',
      cancelText: 'Cancelar',
    });
    if (!confirmed) {
      return;
    }
    this.candidateService.reactivate(id);
  }
}
