// frontend/src/app/features/admin/users/admin-users-page.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { useRoles, useServices, useUsers } from '../../../core/di/services-context';
import { errorText } from '../../../core/i18n/translatable-error';
import { AppError } from '../../../shared/models/error.models';
import type { AdminUser } from './profile.service';

const EMPTY = { displayName: '', email: '', roleName: 'readonly' };

export function AdminUsersPage() {
  const { t } = useTranslation();
  const { profileService, roleService, toastService, confirmDialogService } = useServices();
  const users = useUsers();
  const roles = useRoles();
  const [draft, setDraft] = useState(EMPTY);
  const [error, setError] = useState('');

  useEffect(() => {
    void Promise.all([profileService.load(), roleService.load()]).catch((err) =>
      setError(adminError(err, t)),
    );
  }, [profileService, roleService, t]);

  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    try {
      await profileService.create(draft);
      setDraft({ ...EMPTY, roleName: roles[0]?.name ?? 'readonly' });
      toastService.show(t('admin.users.created'), 'success');
    } catch (err) {
      setError(adminError(err, t));
    }
  };

  const changeRole = async (user: AdminUser, roleName: string) => {
    try {
      await profileService.setRole(user, roleName);
      toastService.show(t('admin.users.roleUpdated'), 'success');
    } catch (err) {
      setError(adminError(err, t));
    }
  };

  const changeActive = async (user: AdminUser) => {
    const isActive = !user.isActive;
    const confirmed = await confirmDialogService.confirm({
      title: t(isActive ? 'admin.users.reactivateTitle' : 'admin.users.deactivateTitle'),
      message: t(isActive ? 'admin.users.reactivateMessage' : 'admin.users.deactivateMessage', {
        name: user.displayName,
      }),
      confirmText: t(isActive ? 'admin.users.reactivate' : 'admin.users.deactivate'),
      cancelText: t('admin.common.cancel'),
      danger: !isActive,
    });
    if (!confirmed) return;
    try {
      await profileService.setActive(user, isActive);
      toastService.show(t('admin.users.stateUpdated'), 'success');
    } catch (err) {
      setError(adminError(err, t));
    }
  };

  return (
    <section className="page">
      <div className="page-header">
        <h1>{t('admin.users.title')}</h1>
        <p className="muted">{t('admin.users.subtitle')}</p>
      </div>
      <form className="panel grid two" onSubmit={create} noValidate>
        <div className="field">
          <label htmlFor="displayName">{t('admin.users.name')}</label>
          <input
            id="displayName"
            name="displayName"
            data-testid="user-display-name"
            value={draft.displayName}
            onChange={(e) => setDraft({ ...draft, displayName: e.target.value })}
            required
          />
        </div>
        <div className="field">
          <label htmlFor="user-email">{t('admin.users.email')}</label>
          <input
            id="user-email"
            name="email"
            data-testid="user-email"
            type="email"
            value={draft.email}
            onChange={(e) => setDraft({ ...draft, email: e.target.value })}
            required
          />
        </div>
        <div className="field">
          <label htmlFor="user-role">{t('admin.users.role')}</label>
          <select
            id="user-role"
            name="roleName"
            data-testid="user-role"
            value={draft.roleName}
            onChange={(e) => setDraft({ ...draft, roleName: e.target.value })}
          >
            {roles
              .filter((role) => role.isActive)
              .map((role) => (
                <option key={role.id} value={role.name}>
                  {role.label}
                </option>
              ))}
          </select>
        </div>
        {error ? (
          <p className="muted span-all" role="alert">
            {error}
          </p>
        ) : null}
        <div className="form-actions span-all">
          <button className="button" type="submit" data-testid="create-user">
            {t('admin.users.create')}
          </button>
        </div>
      </form>
      <div className="panel table-wrap">
        <table>
          <thead>
            <tr>
              <th>{t('admin.users.name')}</th>
              <th>{t('admin.users.email')}</th>
              <th>{t('admin.users.role')}</th>
              <th>{t('admin.users.state')}</th>
              <th>{t('admin.common.actions')}</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user.id}>
                <td>{user.displayName}</td>
                <td>{user.email}</td>
                <td>
                  <select
                    name={`role_${user.id}`}
                    data-testid={`user-role-${user.id}`}
                    value={user.roleName}
                    onChange={(e) => void changeRole(user, e.target.value)}
                  >
                    {roles.map((role) => (
                      <option key={role.id} value={role.name}>
                        {role.label}
                      </option>
                    ))}
                  </select>
                </td>
                <td>
                  <span className="badge">
                    {t(user.isActive ? 'admin.common.active' : 'admin.common.inactive')}
                  </span>
                </td>
                <td>
                  <button
                    className={user.isActive ? 'button danger' : 'button secondary'}
                    type="button"
                    data-testid={`user-active-${user.id}`}
                    onClick={() => void changeActive(user)}
                  >
                    {t(user.isActive ? 'admin.users.deactivate' : 'admin.users.reactivate')}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function adminError(err: unknown, t: ReturnType<typeof useTranslation>['t']): string {
  if (err instanceof AppError && err.backendCode) {
    const key = `admin.errors.${err.backendCode}`;
    return t(key, { defaultValue: errorText(err, t) });
  }
  return errorText(err, t);
}

// src/app/features/admin/users/admin-users-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../core/auth/auth.service';
import { ToastService } from '../../../core/services/toast.service';
import { ProfileService } from './profile.service';
import { RoleService } from '../roles/role.service';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-admin-users-page',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="page">
      <div class="page-header">
        <h1>Usuarios</h1>
        <p class="muted">Alta y mantenimiento de usuarios internos por rol.</p>
      </div>

      <form class="panel grid two" (ngSubmit)="createUser()">
        <div class="field">
          <label>Nombre</label>
          <input name="displayName" [(ngModel)]="draft.displayName" required />
        </div>
        <div class="field">
          <label>Email</label>
          <input name="email" type="email" [(ngModel)]="draft.email" required />
        </div>
        <div class="field">
          <label>Rol</label>
          <select name="role" [(ngModel)]="draft.role" required>
            @for (role of roleService.roles(); track role.name) {
              <option [value]="role.name">{{ role.label }}</option>
            }
          </select>
        </div>
        <div class="field">
          <label class="inline-check">
            <input name="mfa" type="checkbox" [(ngModel)]="draft.mfaRequired" />
            Requerir MFA
          </label>
        </div>
        <div class="form-actions" style="grid-column: 1 / -1;">
          <button class="button" type="submit">Crear usuario</button>
        </div>
      </form>

      <div class="panel table-wrap">
        @if (!users.users().length) {
          <p class="empty-state">
            No hay usuarios cargados. Crea el primero para iniciar la operación.
          </p>
        }
        <table>
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Email</th>
              <th>Rol</th>
              <th>Estado</th>
              <th>MFA</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (user of users.users(); track user.id) {
              <tr>
                <td>{{ user.displayName }}</td>
                <td>{{ user.email }}</td>
                <td>
                  <select
                    [ngModel]="user.role"
                    (ngModelChange)="changeRole(user.id, $event)"
                    [name]="'role_' + user.id"
                  >
                    @for (role of roleService.roles(); track role.name) {
                      <option [value]="role.name">{{ role.label }}</option>
                    }
                  </select>
                </td>
                <td>
                  <span class="badge">{{ user.isActive ? 'Activo' : 'Inactivo' }}</span>
                </td>
                <td>
                  <span class="badge">{{ user.mfaRequired ? 'Obligatoria' : 'Opcional' }}</span>
                </td>
                <td>
                  <div class="form-actions">
                    <button class="button secondary" type="button" (click)="toggleActive(user.id)">
                      {{ user.isActive ? 'Desactivar' : 'Activar' }}
                    </button>
                    <button class="button secondary" type="button" (click)="toggleMfa(user.id)">
                      Cambiar MFA
                    </button>
                    <button class="button danger" type="button" (click)="remove(user.id)">
                      Eliminar
                    </button>
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </section>
  `,
})
export class AdminUsersPageComponent {
  draft = {
    displayName: '',
    email: '',
    role: 'rrhh_user',
    isActive: true,
    mfaRequired: false,
  };

  constructor(
    private readonly auth: AuthService,
    readonly users: ProfileService,
    readonly roleService: RoleService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  createUser(): void {
    try {
      this.users.create(this.draft);
      this.draft = {
        displayName: '',
        email: '',
        role: this.roleService.roles()[0]?.name || 'rrhh_user',
        isActive: true,
        mfaRequired: false,
      };
      this.toast.show('Usuario creado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo crear el usuario.',
        'error',
      );
    }
  }

  changeRole(userId: string, role: string): void {
    try {
      this.users.updateRole(userId, role, this.auth.profile()?.email);
      this.toast.show('Rol actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el rol.',
        'error',
      );
    }
  }

  toggleActive(userId: string): void {
    try {
      this.users.toggleActive(userId, this.auth.profile()?.email);
      this.toast.show('Estado actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el estado.',
        'error',
      );
    }
  }

  toggleMfa(userId: string): void {
    try {
      this.users.toggleMfa(userId);
      this.toast.show('MFA actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar MFA.',
        'error',
      );
    }
  }

  async remove(userId: string): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Eliminar usuario',
      message: 'Esta acción retirará el usuario de la operación actual.',
      confirmText: 'Eliminar usuario',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }
    try {
      this.users.remove(userId, this.auth.profile()?.email);
      this.toast.show('Usuario eliminado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo eliminar el usuario.',
        'error',
      );
    }
  }
}
