// src/app/features/admin/roles/admin-roles-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ToastService } from '../../../core/services/toast.service';
import { Permission, RoleDefinition } from '../../../shared/models/auth.models';
import { ProfileService } from '../users/profile.service';
import { RoleService } from './role.service';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-admin-roles-page',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="page">
      <div class="page-header">
        <h1>Roles</h1>
        <p class="muted">Gestiona roles y permisos funcionales para operar la aplicación.</p>
      </div>

      <form class="panel grid two" (ngSubmit)="createRole()">
        <div class="field">
          <label>Nombre interno</label>
          <input
            name="name"
            [(ngModel)]="newRoleName"
            placeholder="ej: recruiter_junior"
            required
          />
        </div>
        <div class="field">
          <label>Etiqueta visible</label>
          <input
            name="label"
            [(ngModel)]="newRoleLabel"
            placeholder="ej: Recruiter Junior"
            required
          />
        </div>
        <div class="form-actions" style="grid-column: 1 / -1;">
          <button class="button" type="submit">Crear rol</button>
        </div>
      </form>

      <div class="grid two">
        @for (role of roles.roles(); track role.name) {
          <article class="panel stack">
            <div class="toolbar">
              @if (editingRole === role.name) {
                <input name="editLabel" [(ngModel)]="editLabel" />
                <button class="button" type="button" (click)="saveLabel(role)">Guardar</button>
              } @else {
                <h2>{{ role.label }}</h2>
                <button class="button secondary" type="button" (click)="startEditLabel(role)">
                  Editar nombre
                </button>
              }
            </div>
            <p class="muted">
              {{ role.name }} · {{ role.isSystem ? 'Rol de sistema' : 'Rol personalizado' }}
            </p>
            <div class="grid">
              @for (permission of roles.allPermissions; track permission) {
                <label class="inline-check">
                  <input
                    type="checkbox"
                    [checked]="hasPermission(role, permission)"
                    (change)="togglePermission(role, permission, $any($event.target).checked)"
                  />
                  {{ permission }}
                </label>
              }
            </div>
            <div class="form-actions">
              <button
                class="button danger"
                type="button"
                [disabled]="role.isSystem || isRoleInUse(role.name)"
                (click)="remove(role)"
              >
                Eliminar rol
              </button>
            </div>
          </article>
        }
      </div>
    </section>
  `,
})
export class AdminRolesPageComponent {
  newRoleName = '';
  newRoleLabel = '';
  editingRole = '';
  editLabel = '';

  constructor(
    readonly roles: RoleService,
    private readonly users: ProfileService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  createRole(): void {
    try {
      this.roles.create(this.newRoleName, this.newRoleLabel);
      this.newRoleName = '';
      this.newRoleLabel = '';
      this.toast.show('Rol creado.', 'success');
    } catch (error) {
      this.toast.show(error instanceof Error ? error.message : 'No se pudo crear el rol.', 'error');
    }
  }

  startEditLabel(role: RoleDefinition): void {
    this.editingRole = role.name;
    this.editLabel = role.label;
  }

  saveLabel(role: RoleDefinition): void {
    try {
      this.roles.updateLabel(role.name, this.editLabel);
      this.editingRole = '';
      this.editLabel = '';
      this.toast.show('Rol actualizado.', 'success');
    } catch (error) {
      this.toast.show(error instanceof Error ? error.message : 'No se pudo actualizar.', 'error');
    }
  }

  hasPermission(role: RoleDefinition, permission: Permission): boolean {
    return role.permissions.includes(permission);
  }

  togglePermission(role: RoleDefinition, permission: Permission, enabled: boolean): void {
    try {
      this.roles.setPermission(role.name, permission, enabled);
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar permisos.',
        'error',
      );
    }
  }

  isRoleInUse(roleName: string): boolean {
    return this.users.users().some((user) => user.role === roleName);
  }

  async remove(role: RoleDefinition): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Eliminar rol',
      message: `Se eliminará el rol "${role.label}".`,
      confirmText: 'Eliminar rol',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }

    try {
      this.roles.remove(role.name);
      this.toast.show('Rol eliminado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo eliminar el rol.',
        'error',
      );
    }
  }
}

// frontend/src/app/features/admin/roles/admin-roles-page.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { useRoles, useServices } from '../../../core/di/services-context';
import { errorText } from '../../../core/i18n/translatable-error';
import { FormError } from '../../../shared/components/form-error';
import { AppError } from '../../../shared/models/error.models';
import type { Permission } from '../../../shared/models/auth.models';
import type { AdminRole } from './role.service';

export function AdminRolesPage() {
  const { t } = useTranslation();
  const { roleService, toastService, confirmDialogService } = useServices();
  const roles = useRoles();
  const [name, setName] = useState('');
  const [label, setLabel] = useState('');
  const [editedLabels, setEditedLabels] = useState<Record<string, string>>({});
  const [error, setError] = useState('');
  useEffect(() => {
    void roleService.load().catch((err) => setError(roleError(err, t)));
  }, [roleService, t]);
  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    try {
      await roleService.create(name, label);
      setName('');
      setLabel('');
      toastService.show(t('admin.roles.created'), 'success');
    } catch (err) {
      setError(roleError(err, t));
    }
  };
  const togglePermission = async (role: AdminRole, permission: Permission, enabled: boolean) => {
    const permissions = enabled
      ? [...new Set([...role.permissions, permission])]
      : role.permissions.filter((item) => item !== permission);
    try {
      await roleService.setPermissions(role, permissions);
    } catch (err) {
      setError(roleError(err, t));
    }
  };
  const saveLabel = async (role: AdminRole) => {
    try {
      await roleService.updateLabel(role, editedLabels[role.id] ?? role.label);
      setEditedLabels((current) => {
        const next = { ...current };
        delete next[role.id];
        return next;
      });
      toastService.show(t('admin.roles.labelUpdated'), 'success');
    } catch (err) {
      setError(roleError(err, t));
    }
  };
  const changeActive = async (role: AdminRole) => {
    const isActive = !role.isActive;
    const confirmed = await confirmDialogService.confirm({
      title: t(isActive ? 'admin.roles.reactivateTitle' : 'admin.roles.deactivateTitle'),
      message: t(isActive ? 'admin.roles.reactivateMessage' : 'admin.roles.deactivateMessage', {
        name: role.label,
      }),
      confirmText: t(isActive ? 'admin.roles.reactivate' : 'admin.roles.deactivate'),
      cancelText: t('admin.common.cancel'),
      danger: !isActive,
    });
    if (!confirmed) return;
    try {
      await roleService.setActive(role, isActive);
    } catch (err) {
      setError(roleError(err, t));
    }
  };
  return (
    <section className="page">
      <div className="page-header">
        <h1>{t('admin.roles.title')}</h1>
        <p className="muted">{t('admin.roles.subtitle')}</p>
      </div>
      <form className="panel grid two" onSubmit={create} noValidate>
        <FormError message={error} className="span-all" />
        <div className="field">
          <label htmlFor="role-name">{t('admin.roles.name')}</label>
          <input
            id="role-name"
            name="name"
            data-testid="role-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
        </div>
        <div className="field">
          <label htmlFor="role-label">{t('admin.roles.label')}</label>
          <input
            id="role-label"
            name="label"
            data-testid="role-label"
            value={label}
            onChange={(e) => setLabel(e.target.value)}
          />
        </div>
        <div className="form-actions span-all">
          <button className="button" type="submit" data-testid="create-role">
            {t('admin.roles.create')}
          </button>
        </div>
      </form>
      <div className="grid two">
        {roles.map((role) => (
          <article className="panel stack" key={role.id}>
            <div className="toolbar">
              <h2>{role.label}</h2>
              <div className="toolbar">
                <span className="badge">
                  {t(role.isSystem ? 'admin.roles.system' : 'admin.roles.custom')}
                </span>
                <span
                  className="badge"
                  data-testid={`role-status-${role.name}`}
                  data-status={role.isActive ? 'active' : 'inactive'}
                >
                  {t(role.isActive ? 'admin.common.active' : 'admin.common.inactive')}
                </span>
              </div>
            </div>
            <p className="muted">{role.name}</p>
            <div className="field">
              <label htmlFor={`role-label-${role.name}`}>{t('admin.roles.label')}</label>
              <div className="toolbar">
                <input
                  id={`role-label-${role.name}`}
                  name={`label_${role.name}`}
                  data-testid={`role-label-${role.name}`}
                  value={editedLabels[role.id] ?? role.label}
                  onChange={(event) =>
                    setEditedLabels((current) => ({
                      ...current,
                      [role.id]: event.target.value,
                    }))
                  }
                />
                <button
                  className="button secondary"
                  type="button"
                  data-testid={`role-label-save-${role.name}`}
                  onClick={() => void saveLabel(role)}
                >
                  {t('admin.roles.saveLabel')}
                </button>
              </div>
            </div>
            <div className="grid">
              {roleService.allPermissions.map((permission) => (
                <label className="inline-check" key={permission}>
                  <input
                    name={`${role.name}_${permission}`}
                    data-testid={`${role.name}-${permission}`}
                    type="checkbox"
                    checked={role.permissions.includes(permission)}
                    disabled={!role.isActive}
                    onChange={(e) => void togglePermission(role, permission, e.target.checked)}
                  />
                  {permission}
                </label>
              ))}
            </div>
            <div className="form-actions">
              <button
                className={role.isActive ? 'button danger' : 'button secondary'}
                type="button"
                data-testid={`role-active-${role.id}`}
                disabled={role.isSystem}
                title={role.isSystem ? t('admin.roles.systemProtected') : undefined}
                onClick={() => void changeActive(role)}
              >
                {t(role.isActive ? 'admin.roles.deactivate' : 'admin.roles.reactivate')}
              </button>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}

function roleError(err: unknown, t: ReturnType<typeof useTranslation>['t']): string {
  if (err instanceof AppError && err.backendCode)
    return t(`admin.errors.${err.backendCode}`, { defaultValue: errorText(err, t) });
  return errorText(err, t);
}
