// src/app/features/candidates/components/candidate-programs.tsx
import { useState, type FormEvent } from 'react';
import { useServices } from '../../../core/di/services-context';
import { useCatalogs } from '../../catalogs/use-catalogs';
import type { CandidateProgram } from '../models/candidate.models';

interface Draft {
  program: string;
  level: string;
  yearsExperience: number | undefined;
}

const EMPTY: Draft = { program: '', level: '', yearsExperience: undefined };

interface Props {
  candidateId: string;
  programs: CandidateProgram[];
  canEdit: boolean;
}

export function CandidatePrograms({ candidateId, programs, canEdit }: Props) {
  const { candidateRelationsService } = useServices();
  const catalogs = useCatalogs();
  const [draft, setDraft] = useState<Draft>(EMPTY);
  const [error, setError] = useState('');

  const programOptions = catalogs.activeNames('program');
  const levelOptions = catalogs.activeNames('program_level');

  const add = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    try {
      candidateRelationsService.addProgram(candidateId, { ...draft });
      setDraft(EMPTY);
      setError('');
    } catch (err) {
      setError((err as Error).message);
    }
  };

  return (
    <section className="section-block" data-testid="candidate-programs">
      <h3 className="section-title">Programas</h3>
      {!programs.length ? <p className="empty-state">Sin programas asociados.</p> : null}
      <div className="item-list">
        {programs.map((item) => (
          <div className="item-row" key={item.id}>
            <p className="item-main">
              <span className="badge">{item.program}</span> {item.level}
              {item.yearsExperience !== undefined ? ` (${item.yearsExperience} años)` : ''}
            </p>
            {canEdit ? (
              <button
                className="button secondary"
                type="button"
                onClick={() => candidateRelationsService.removeProgram(candidateId, item.id)}
              >
                Quitar
              </button>
            ) : null}
          </div>
        ))}
      </div>
      {canEdit ? (
        <form className="section-block" onSubmit={add} noValidate>
          <div className="grid two">
            <div className="field">
              <label htmlFor="program">Programa</label>
              <select
                id="program"
                name="program"
                value={draft.program}
                onChange={(e) => setDraft({ ...draft, program: e.target.value })}
                required
              >
                <option value="" disabled>
                  Selecciona
                </option>
                {programOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="program-level">Nivel</label>
              <select
                id="program-level"
                name="level"
                value={draft.level}
                onChange={(e) => setDraft({ ...draft, level: e.target.value })}
                required
              >
                <option value="" disabled>
                  Selecciona
                </option>
                {levelOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="program-years">Años de experiencia</label>
              <input
                id="program-years"
                name="yearsExperience"
                type="number"
                min="0"
                value={draft.yearsExperience ?? ''}
                // ngModel coerced to number; React hands back a string.
                onChange={(e) =>
                  setDraft({
                    ...draft,
                    yearsExperience: e.target.value === '' ? undefined : Number(e.target.value),
                  })
                }
              />
            </div>
          </div>
          {error ? <p className="empty-state">{error}</p> : null}
          <div className="form-actions">
            <button className="button" type="submit">
              Añadir programa
            </button>
          </div>
        </form>
      ) : null}
    </section>
  );
}

// src/app/features/candidates/components/candidate-programs.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CatalogService } from '../../catalogs/services/catalog.service';
import { CandidateProgram } from '../models/candidate.models';
import { CandidateRelationsService } from '../services/candidate-relations.service';

@Component({
  selector: 'rrhh-candidate-programs',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="section-block">
      <h3 class="section-title">Programas</h3>
      @if (!programs.length) {
        <p class="empty-state">Sin programas asociados.</p>
      }
      <div class="item-list">
        @for (item of programs; track item.id) {
          <div class="item-row">
            <p class="item-main">
              <span class="badge">{{ item.program }}</span> {{ item.level }}
              @if (item.yearsExperience !== undefined) {
                ({{ item.yearsExperience }} años)
              }
            </p>
            @if (canEdit) {
              <button class="button secondary" type="button" (click)="remove(item.id)">
                Quitar
              </button>
            }
          </div>
        }
      </div>
      @if (canEdit) {
        <form class="section-block" (ngSubmit)="add()">
          <div class="grid two">
            <div class="field">
              <label>Programa</label>
              <select name="program" [(ngModel)]="draft.program" required>
                <option value="" disabled>Selecciona</option>
                @for (option of programOptions; track option) {
                  <option [value]="option">{{ option }}</option>
                }
              </select>
            </div>
            <div class="field">
              <label>Nivel</label>
              <select name="level" [(ngModel)]="draft.level" required>
                <option value="" disabled>Selecciona</option>
                @for (option of levelOptions; track option) {
                  <option [value]="option">{{ option }}</option>
                }
              </select>
            </div>
            <div class="field">
              <label>Años de experiencia</label>
              <input
                name="yearsExperience"
                type="number"
                min="0"
                [(ngModel)]="draft.yearsExperience"
              />
            </div>
          </div>
          @if (error) {
            <p class="empty-state">{{ error }}</p>
          }
          <div class="form-actions">
            <button class="button" type="submit">Añadir programa</button>
          </div>
        </form>
      }
    </section>
  `,
})
export class CandidateProgramsComponent {
  @Input() candidateId = '';
  @Input() programs: CandidateProgram[] = [];
  @Input() canEdit = false;

  draft: { program: string; level: string; yearsExperience: number | undefined } = {
    program: '',
    level: '',
    yearsExperience: undefined,
  };
  error = '';

  constructor(
    private readonly relations: CandidateRelationsService,
    private readonly catalogs: CatalogService,
  ) {}

  get programOptions(): string[] {
    return this.catalogs.activeNames('program');
  }

  get levelOptions(): string[] {
    return this.catalogs.activeNames('program_level');
  }

  add(): void {
    try {
      this.relations.addProgram(this.candidateId, { ...this.draft });
      this.draft = { program: '', level: '', yearsExperience: undefined };
      this.error = '';
    } catch (err) {
      this.error = (err as Error).message;
    }
  }

  remove(programId: string): void {
    this.relations.removeProgram(this.candidateId, programId);
  }
}
