// src/app/features/candidates/components/candidate-documents.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../core/auth/auth.service';
import { ToastService } from '../../../core/services/toast.service';
import { DocumentService } from '../../documents/services/document.service';
import { Candidate } from '../models/candidate.models';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-candidate-documents',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="section-block">
      <h3 class="section-title">Documentos</h3>
      @if (!candidate?.documents?.length) {
        <p class="empty-state">Sin CV adjunto.</p>
      }
      <div class="item-list">
        @for (document of candidate?.documents ?? []; track document.id) {
          <div class="item-row">
            <p class="item-main">
              <strong>{{ document.originalFilename }}</strong>
              <span class="badge">{{
                document.isPrimary ? 'Principal' : document.documentType
              }}</span>
            </p>
            <button
              class="button secondary"
              type="button"
              [disabled]="!auth.hasPermission('download_candidate_documents')"
              (click)="open(document.id)"
            >
              Abrir seguro
            </button>
            @if (auth.hasPermission('upload_candidate_documents') && !document.isPrimary) {
              <button class="button ghost" type="button" (click)="markPrimary(document.id)">
                Marcar principal
              </button>
            }
            @if (auth.hasPermission('upload_candidate_documents')) {
              <button class="button danger" type="button" (click)="remove(document.id)">
                Eliminar
              </button>
            }
          </div>
        }
      </div>
      @if (auth.hasPermission('upload_candidate_documents')) {
        <form class="section-block" (ngSubmit)="upload()">
          <div class="grid two">
            <div class="field">
              <label>Archivo CV (PDF)</label>
              <input
                name="file"
                type="file"
                accept="application/pdf"
                (change)="onFileSelected($event)"
              />
            </div>
            <div class="field">
              <label class="inline-check">
                <input name="isPrimary" type="checkbox" [(ngModel)]="isPrimary" />
                Marcar como CV principal
              </label>
            </div>
          </div>
          @if (error) {
            <p class="empty-state">{{ error }}</p>
          }
          <div class="form-actions">
            <button class="button" type="submit" [disabled]="!selectedFile">Subir CV</button>
          </div>
        </form>
      }
    </section>
  `,
})
export class CandidateDocumentsComponent {
  @Input() candidate: Candidate | undefined;

  selectedFile: File | undefined;
  isPrimary = true;
  error = '';

  constructor(
    readonly auth: AuthService,
    private readonly documentService: DocumentService,
    private readonly toast: ToastService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.selectedFile = input.files?.[0];
  }

  upload(): void {
    if (!this.candidate || !this.selectedFile) {
      return;
    }
    try {
      this.documentService.upload({
        candidateId: this.candidate.id,
        file: this.selectedFile,
        isPrimary: this.isPrimary,
      });
      this.selectedFile = undefined;
      this.isPrimary = true;
      this.error = '';
      this.toast.show('CV subido correctamente.', 'success');
    } catch (err) {
      this.error = (err as Error).message;
    }
  }

  open(documentId: string): void {
    if (!this.candidate) {
      return;
    }
    const secure = this.documentService.createSecureUrl(this.candidate.id, documentId);
    window.open(secure.url, '_blank', 'noopener,noreferrer');
  }

  markPrimary(documentId: string): void {
    if (!this.candidate) {
      return;
    }

    try {
      this.documentService.setPrimary(this.candidate.id, documentId);
      this.toast.show('CV principal actualizado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo actualizar el CV.',
        'error',
      );
    }
  }

  async remove(documentId: string): Promise<void> {
    if (!this.candidate) {
      return;
    }

    const confirmed = await this.confirmDialog.confirm({
      title: 'Eliminar documento',
      message: 'Se eliminará el documento seleccionado del candidato.',
      confirmText: 'Eliminar documento',
      cancelText: 'Cancelar',
      danger: true,
    });

    if (!confirmed) {
      return;
    }

    try {
      this.documentService.remove(this.candidate.id, documentId);
      this.toast.show('Documento eliminado.', 'success');
    } catch (error) {
      this.toast.show(
        error instanceof Error ? error.message : 'No se pudo eliminar el documento.',
        'error',
      );
    }
  }
}

// src/app/features/candidates/components/candidate-documents.tsx
import { useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { usePermission, useServices } from '../../../core/di/services-context';
import type { Candidate } from '../models/candidate.models';

export function CandidateDocuments({ candidate }: { candidate: Candidate | undefined }) {
  const { documentService, toastService, confirmDialogService } = useServices();
  const [selectedFile, setSelectedFile] = useState<File | undefined>(undefined);
  const [isPrimary, setIsPrimary] = useState(true);
  const [error, setError] = useState('');
  const fileInput = useRef<HTMLInputElement>(null);

  const canDownload = usePermission('download_candidate_documents');
  const canUpload = usePermission('upload_candidate_documents');

  const onFileSelected = (event: ChangeEvent<HTMLInputElement>): void => {
    setSelectedFile(event.target.files?.[0]);
  };

  const upload = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    if (!candidate || !selectedFile) {
      return;
    }
    try {
      documentService.upload({ candidateId: candidate.id, file: selectedFile, isPrimary });
      setSelectedFile(undefined);
      setIsPrimary(true);
      setError('');
      // The file input is uncontrolled; clear it so the same file can be re-picked.
      if (fileInput.current) {
        fileInput.current.value = '';
      }
      toastService.show('CV subido correctamente.', 'success');
    } catch (err) {
      setError((err as Error).message);
    }
  };

  const open = (documentId: string): void => {
    if (!candidate) {
      return;
    }
    const secure = documentService.createSecureUrl(candidate.id, documentId);
    window.open(secure.url, '_blank', 'noopener,noreferrer');
  };

  const markPrimary = (documentId: string): void => {
    if (!candidate) {
      return;
    }
    try {
      documentService.setPrimary(candidate.id, documentId);
      toastService.show('CV principal actualizado.', 'success');
    } catch (err) {
      toastService.show(
        err instanceof Error ? err.message : 'No se pudo actualizar el CV.',
        'error',
      );
    }
  };

  const remove = async (documentId: string): Promise<void> => {
    if (!candidate) {
      return;
    }
    const confirmed = await confirmDialogService.confirm({
      title: 'Eliminar documento',
      message: 'Se eliminará el documento seleccionado del candidato.',
      confirmText: 'Eliminar documento',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }
    try {
      documentService.remove(candidate.id, documentId);
      toastService.show('Documento eliminado.', 'success');
    } catch (err) {
      toastService.show(
        err instanceof Error ? err.message : 'No se pudo eliminar el documento.',
        'error',
      );
    }
  };

  const documents = candidate?.documents ?? [];

  return (
    <section className="section-block" data-testid="candidate-documents">
      <h3 className="section-title">Documentos</h3>
      {!documents.length ? <p className="empty-state">Sin CV adjunto.</p> : null}
      <div className="item-list">
        {documents.map((document) => (
          <div className="item-row" key={document.id}>
            <p className="item-main">
              <strong>{document.originalFilename}</strong>
              <span className="badge">
                {document.isPrimary ? 'Principal' : document.documentType}
              </span>
            </p>
            <button
              className="button secondary"
              type="button"
              disabled={!canDownload}
              onClick={() => open(document.id)}
            >
              Abrir seguro
            </button>
            {canUpload && !document.isPrimary ? (
              <button
                className="button ghost"
                type="button"
                onClick={() => markPrimary(document.id)}
              >
                Marcar principal
              </button>
            ) : null}
            {canUpload ? (
              <button className="button danger" type="button" onClick={() => remove(document.id)}>
                Eliminar
              </button>
            ) : null}
          </div>
        ))}
      </div>
      {canUpload ? (
        <form className="section-block" onSubmit={upload} noValidate>
          <div className="grid two">
            <div className="field">
              <label htmlFor="file">Archivo CV (PDF)</label>
              <input
                id="file"
                ref={fileInput}
                name="file"
                type="file"
                accept="application/pdf"
                onChange={onFileSelected}
              />
            </div>
            <div className="field">
              <label className="inline-check">
                <input
                  name="isPrimary"
                  type="checkbox"
                  checked={isPrimary}
                  onChange={(e) => setIsPrimary(e.target.checked)}
                />
                Marcar como CV principal
              </label>
            </div>
          </div>
          {error ? <p className="empty-state">{error}</p> : null}
          <div className="form-actions">
            <button className="button" type="submit" disabled={!selectedFile}>
              Subir CV
            </button>
          </div>
        </form>
      ) : null}
    </section>
  );
}
