// src/app/features/candidates/components/candidate-form.tsx
import { useState, type FormEvent } from 'react';
import type { Candidate, CandidateDraft } from '../models/candidate.models';
import { toDraft } from './candidate-form.logic';
import { CandidateTags } from './candidate-tags';

interface CandidateFormProps {
  candidate?: Candidate;
  onSave: (draft: CandidateDraft) => void;
}

export function CandidateForm({ candidate, onSave }: CandidateFormProps) {
  // Initialiser only. The parent passes `key` so switching candidate remounts
  // and resets the draft, which is what the Angular input setter did.
  const [draft, setDraft] = useState<CandidateDraft>(() => toDraft(candidate));
  const [error, setError] = useState('');

  const set =
    (key: keyof CandidateDraft) =>
    (event: { target: { value: string } }): void =>
      setDraft((current) => ({ ...current, [key]: event.target.value }));

  const submit = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    if (!draft.firstName.trim() || !draft.lastName.trim()) {
      setError('Nombre y apellidos son obligatorios.');
      return;
    }
    setError('');
    onSave({ ...draft });
  };

  return (
    <>
      <form className="section-block" onSubmit={submit} noValidate>
        <div className="grid two">
          <div className="field">
            <label htmlFor="firstName">Nombre</label>
            <input
              id="firstName"
              name="firstName"
              value={draft.firstName}
              onChange={set('firstName')}
              required
            />
          </div>
          <div className="field">
            <label htmlFor="lastName">Apellidos</label>
            <input
              id="lastName"
              name="lastName"
              value={draft.lastName}
              onChange={set('lastName')}
              required
            />
          </div>
          <div className="field">
            <label htmlFor="phone">Teléfono</label>
            <input id="phone" name="phone" value={draft.phone} onChange={set('phone')} />
          </div>
          <div className="field">
            <label htmlFor="email">Email</label>
            <input
              id="email"
              name="email"
              type="email"
              value={draft.email}
              onChange={set('email')}
            />
          </div>
          <div className="field">
            <label htmlFor="location">Localidad</label>
            <input
              id="location"
              name="location"
              value={draft.location}
              onChange={set('location')}
            />
          </div>
          <div className="field">
            <label htmlFor="province">Provincia</label>
            <input
              id="province"
              name="province"
              value={draft.province}
              onChange={set('province')}
            />
          </div>
          <div className="field">
            <label htmlFor="availability">Disponibilidad</label>
            <input
              id="availability"
              name="availability"
              value={draft.availability}
              onChange={set('availability')}
            />
          </div>
          <div className="field">
            <label htmlFor="status">Estado</label>
            <select id="status" name="status" value={draft.status} onChange={set('status')}>
              <option value="new">Nuevo</option>
              <option value="available">Disponible</option>
              <option value="in_process">En proceso</option>
              <option value="hired">Contratado</option>
              <option value="rejected">Descartado</option>
            </select>
          </div>
          <div className="field">
            <label htmlFor="receivedAt">Fecha recepción</label>
            <input
              id="receivedAt"
              name="receivedAt"
              type="date"
              value={draft.receivedAt}
              onChange={set('receivedAt')}
            />
          </div>
          <div className="field">
            <label htmlFor="reviewDueAt">Fecha revisión</label>
            <input
              id="reviewDueAt"
              name="reviewDueAt"
              type="date"
              value={draft.reviewDueAt}
              onChange={set('reviewDueAt')}
            />
          </div>
        </div>
        <div className="field">
          <label htmlFor="notes">Observaciones internas</label>
          <textarea id="notes" name="notes" rows={4} value={draft.notes} onChange={set('notes')} />
        </div>
        {error ? <p className="empty-state">{error}</p> : null}
        <div className="form-actions">
          <button className="button" type="submit">
            Guardar
          </button>
        </div>
      </form>
      {candidate ? <CandidateTags candidateId={candidate.id} tags={candidate.tags} /> : null}
    </>
  );
}

// src/app/features/candidates/components/candidate-form.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  Candidate,
  CandidateDraft,
  CandidateStatus,
  EMPTY_CANDIDATE_DRAFT,
} from '../models/candidate.models';

@Component({
  selector: 'rrhh-candidate-form',
  standalone: true,
  imports: [FormsModule],
  template: `
    <form class="section-block" (ngSubmit)="submit()">
      <div class="grid two">
        <div class="field">
          <label>Nombre</label>
          <input name="firstName" [(ngModel)]="draft.firstName" required />
        </div>
        <div class="field">
          <label>Apellidos</label>
          <input name="lastName" [(ngModel)]="draft.lastName" required />
        </div>
        <div class="field">
          <label>Teléfono</label>
          <input name="phone" [(ngModel)]="draft.phone" />
        </div>
        <div class="field">
          <label>Email</label>
          <input name="email" type="email" [(ngModel)]="draft.email" />
        </div>
        <div class="field">
          <label>Localidad</label>
          <input name="location" [(ngModel)]="draft.location" />
        </div>
        <div class="field">
          <label>Provincia</label>
          <input name="province" [(ngModel)]="draft.province" />
        </div>
        <div class="field">
          <label>Disponibilidad</label>
          <input name="availability" [(ngModel)]="draft.availability" />
        </div>
        <div class="field">
          <label>Estado</label>
          <select name="status" [(ngModel)]="draft.status">
            <option value="new">Nuevo</option>
            <option value="available">Disponible</option>
            <option value="in_process">En proceso</option>
            <option value="hired">Contratado</option>
            <option value="rejected">Descartado</option>
          </select>
        </div>
        <div class="field">
          <label>Fecha recepción</label>
          <input name="receivedAt" type="date" [(ngModel)]="draft.receivedAt" />
        </div>
        <div class="field">
          <label>Fecha revisión</label>
          <input name="reviewDueAt" type="date" [(ngModel)]="draft.reviewDueAt" />
        </div>
      </div>
      <div class="field">
        <label>Observaciones internas</label>
        <textarea name="notes" rows="4" [(ngModel)]="draft.notes"></textarea>
      </div>
      @if (error) {
        <p class="empty-state">{{ error }}</p>
      }
      <div class="form-actions">
        <button class="button" type="submit">Guardar</button>
      </div>
    </form>
  `,
})
export class CandidateFormComponent {
  @Output() readonly save = new EventEmitter<CandidateDraft>();
  draft: CandidateDraft = structuredClone(EMPTY_CANDIDATE_DRAFT);
  error = '';

  @Input() set candidate(value: Candidate | undefined) {
    if (!value) {
      this.draft = structuredClone(EMPTY_CANDIDATE_DRAFT);
      return;
    }
    const {
      id: _id,
      createdAt: _createdAt,
      updatedAt: _updatedAt,
      languages: _languages,
      programs: _programs,
      education: _education,
      experience: _experience,
      skills: _skills,
      documents: _documents,
      ...draft
    } = value;
    this.draft = { ...draft, status: draft.status as CandidateStatus };
  }

  submit(): void {
    if (!this.draft.firstName.trim() || !this.draft.lastName.trim()) {
      this.error = 'Nombre y apellidos son obligatorios.';
      return;
    }
    this.error = '';
    this.save.emit({ ...this.draft });
  }
}
