// src/app/features/candidates/components/candidate-experience.tsx
import { useState, type FormEvent } from 'react';
import { useServices } from '../../../core/di/services-context';
import { useCatalogs } from '../../catalogs/use-catalogs';
import type { CandidateExperience as CandidateExperienceModel } from '../models/candidate.models';

interface Draft {
  company: string;
  position: string;
  sector: string;
  startDate: string;
  endDate: string;
  yearsExperience: number | undefined;
  isCurrent: boolean;
}

const EMPTY: Draft = {
  company: '',
  position: '',
  sector: '',
  startDate: '',
  endDate: '',
  yearsExperience: undefined,
  isCurrent: false,
};

interface Props {
  candidateId: string;
  experience: CandidateExperienceModel[];
  canEdit: boolean;
}

export function CandidateExperience({ candidateId, experience, canEdit }: Props) {
  const { candidateRelationsService } = useServices();
  const catalogs = useCatalogs();
  const [draft, setDraft] = useState<Draft>(EMPTY);
  const [error, setError] = useState('');

  const sectorOptions = catalogs.activeNames('sector');

  const add = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    try {
      candidateRelationsService.addExperience(candidateId, { ...draft });
      setDraft(EMPTY);
      setError('');
    } catch (err) {
      setError((err as Error).message);
    }
  };

  return (
    <section className="section-block" data-testid="candidate-experience">
      <h3 className="section-title">Experiencia</h3>
      {!experience.length ? <p className="empty-state">Sin experiencia registrada.</p> : null}
      <div className="item-list">
        {experience.map((item) => (
          <div className="item-row" key={item.id}>
            <p className="item-main">
              <span className="badge">{item.position}</span> {item.company} ({item.sector})
              {item.isCurrent
                ? ' · Actual'
                : item.yearsExperience !== undefined
                  ? ` · ${item.yearsExperience} años`
                  : ''}
            </p>
            {canEdit ? (
              <button
                className="button secondary"
                type="button"
                onClick={() => candidateRelationsService.removeExperience(candidateId, item.id)}
              >
                Quitar
              </button>
            ) : null}
          </div>
        ))}
      </div>
      {canEdit ? (
        <form className="section-block" onSubmit={add} noValidate>
          <div className="grid two">
            <div className="field">
              <label htmlFor="company">Empresa</label>
              <input
                id="company"
                name="company"
                value={draft.company}
                onChange={(e) => setDraft({ ...draft, company: e.target.value })}
                required
              />
            </div>
            <div className="field">
              <label htmlFor="position">Puesto</label>
              <input
                id="position"
                name="position"
                value={draft.position}
                onChange={(e) => setDraft({ ...draft, position: e.target.value })}
                required
              />
            </div>
            <div className="field">
              <label htmlFor="sector">Sector</label>
              <select
                id="sector"
                name="sector"
                value={draft.sector}
                onChange={(e) => setDraft({ ...draft, sector: e.target.value })}
                required
              >
                <option value="" disabled>
                  Selecciona
                </option>
                {sectorOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="startDate">Fecha inicio</label>
              <input
                id="startDate"
                name="startDate"
                type="date"
                value={draft.startDate}
                onChange={(e) => setDraft({ ...draft, startDate: e.target.value })}
              />
            </div>
            <div className="field">
              <label htmlFor="endDate">Fecha fin</label>
              <input
                id="endDate"
                name="endDate"
                type="date"
                value={draft.endDate}
                disabled={draft.isCurrent}
                onChange={(e) => setDraft({ ...draft, endDate: e.target.value })}
              />
            </div>
            <div className="field">
              <label htmlFor="experience-years">Años de experiencia</label>
              <input
                id="experience-years"
                name="yearsExperience"
                type="number"
                min="0"
                value={draft.yearsExperience ?? ''}
                onChange={(e) =>
                  setDraft({
                    ...draft,
                    yearsExperience: e.target.value === '' ? undefined : Number(e.target.value),
                  })
                }
              />
            </div>
            <div className="field">
              <label className="inline-check">
                <input
                  name="isCurrent"
                  type="checkbox"
                  checked={draft.isCurrent}
                  onChange={(e) => setDraft({ ...draft, isCurrent: e.target.checked })}
                />
                Puesto actual
              </label>
            </div>
          </div>
          {error ? <p className="empty-state">{error}</p> : null}
          <div className="form-actions">
            <button className="button" type="submit">
              Añadir experiencia
            </button>
          </div>
        </form>
      ) : null}
    </section>
  );
}

// src/app/features/candidates/components/candidate-experience.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CatalogService } from '../../catalogs/services/catalog.service';
import { CandidateExperience } from '../models/candidate.models';
import { CandidateRelationsService } from '../services/candidate-relations.service';

@Component({
  selector: 'rrhh-candidate-experience',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="section-block">
      <h3 class="section-title">Experiencia</h3>
      @if (!experience.length) {
        <p class="empty-state">Sin experiencia registrada.</p>
      }
      <div class="item-list">
        @for (item of experience; track item.id) {
          <div class="item-row">
            <p class="item-main">
              <span class="badge">{{ item.position }}</span> {{ item.company }} ({{ item.sector }})
              @if (item.isCurrent) {
                · Actual
              } @else if (item.yearsExperience !== undefined) {
                · {{ item.yearsExperience }} años
              }
            </p>
            @if (canEdit) {
              <button class="button secondary" type="button" (click)="remove(item.id)">
                Quitar
              </button>
            }
          </div>
        }
      </div>
      @if (canEdit) {
        <form class="section-block" (ngSubmit)="add()">
          <div class="grid two">
            <div class="field">
              <label>Empresa</label>
              <input name="company" [(ngModel)]="draft.company" required />
            </div>
            <div class="field">
              <label>Puesto</label>
              <input name="position" [(ngModel)]="draft.position" required />
            </div>
            <div class="field">
              <label>Sector</label>
              <select name="sector" [(ngModel)]="draft.sector" required>
                <option value="" disabled>Selecciona</option>
                @for (option of sectorOptions; track option) {
                  <option [value]="option">{{ option }}</option>
                }
              </select>
            </div>
            <div class="field">
              <label>Fecha inicio</label>
              <input name="startDate" type="date" [(ngModel)]="draft.startDate" />
            </div>
            <div class="field">
              <label>Fecha fin</label>
              <input
                name="endDate"
                type="date"
                [(ngModel)]="draft.endDate"
                [disabled]="draft.isCurrent"
              />
            </div>
            <div class="field">
              <label>Años de experiencia</label>
              <input
                name="yearsExperience"
                type="number"
                min="0"
                [(ngModel)]="draft.yearsExperience"
              />
            </div>
            <div class="field">
              <label class="inline-check">
                <input name="isCurrent" type="checkbox" [(ngModel)]="draft.isCurrent" />
                Puesto actual
              </label>
            </div>
          </div>
          @if (error) {
            <p class="empty-state">{{ error }}</p>
          }
          <div class="form-actions">
            <button class="button" type="submit">Añadir experiencia</button>
          </div>
        </form>
      }
    </section>
  `,
})
export class CandidateExperienceComponent {
  @Input() candidateId = '';
  @Input() experience: CandidateExperience[] = [];
  @Input() canEdit = false;

  draft: {
    company: string;
    position: string;
    sector: string;
    startDate: string;
    endDate: string;
    yearsExperience: number | undefined;
    isCurrent: boolean;
  } = {
    company: '',
    position: '',
    sector: '',
    startDate: '',
    endDate: '',
    yearsExperience: undefined,
    isCurrent: false,
  };
  error = '';

  constructor(
    private readonly relations: CandidateRelationsService,
    private readonly catalogs: CatalogService,
  ) {}

  get sectorOptions(): string[] {
    return this.catalogs.activeNames('sector');
  }

  add(): void {
    try {
      this.relations.addExperience(this.candidateId, { ...this.draft });
      this.draft = {
        company: '',
        position: '',
        sector: '',
        startDate: '',
        endDate: '',
        yearsExperience: undefined,
        isCurrent: false,
      };
      this.error = '';
    } catch (err) {
      this.error = (err as Error).message;
    }
  }

  remove(experienceId: string): void {
    this.relations.removeExperience(this.candidateId, experienceId);
  }
}
