// src/app/features/candidates/pages/candidate-detail-page.component.ts
import { Component, Input } from '@angular/core';
import { SlicePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../../core/auth/auth.service';
import { CandidateDocumentsComponent } from '../components/candidate-documents.component';
import { CandidateEducationComponent } from '../components/candidate-education.component';
import { CandidateExperienceComponent } from '../components/candidate-experience.component';
import { CandidateLanguagesComponent } from '../components/candidate-languages.component';
import { CandidateProgramsComponent } from '../components/candidate-programs.component';
import { CandidateSkillsComponent } from '../components/candidate-skills.component';
import { CandidateService } from '../services/candidate.service';
import { ConfirmDialogService } from '../../../shared/components/confirm-dialog.service';

@Component({
  selector: 'rrhh-candidate-detail-page',
  standalone: true,
  imports: [
    RouterLink,
    SlicePipe,
    CandidateLanguagesComponent,
    CandidateProgramsComponent,
    CandidateEducationComponent,
    CandidateExperienceComponent,
    CandidateSkillsComponent,
    CandidateDocumentsComponent,
  ],
  template: `
    @if (candidate; as item) {
      <section class="page">
        <div class="toolbar">
          <div class="page-header">
            <h1>{{ item.firstName }} {{ item.lastName }}</h1>
            <p class="muted">{{ item.email }} · {{ item.phone }}</p>
          </div>
          <div class="toolbar">
            @if (auth.hasPermission('edit_candidates')) {
              <a class="button secondary" [routerLink]="['/app/candidates', item.id, 'edit']"
                >Editar</a
              >
              @if (item.isActive) {
                <button class="button danger" type="button" (click)="deactivate(item.id)">
                  Baja lógica
                </button>
              } @else {
                <button class="button secondary" type="button" (click)="reactivate(item.id)">
                  Alta lógica
                </button>
              }
            }
          </div>
        </div>
        <div class="grid two">
          <article class="panel">
            <h2>Datos principales</h2>
            <p><strong>Estado:</strong> {{ item.status }}</p>
            <p><strong>Disponibilidad:</strong> {{ item.availability }}</p>
            <p><strong>Localidad:</strong> {{ item.location }} {{ item.province }}</p>
            <p><strong>Recepción:</strong> {{ item.receivedAt || 'Pendiente' }}</p>
            <p><strong>Revisión:</strong> {{ item.reviewDueAt || 'Pendiente' }}</p>
            <p>{{ item.notes }}</p>
          </article>
          <article class="panel">
            <h2>Auditoría</h2>
            <p><strong>Creado:</strong> {{ item.createdAt | slice: 0 : 19 }}</p>
            <p><strong>Actualizado:</strong> {{ item.updatedAt | slice: 0 : 19 }}</p>
            <p><strong>Activo:</strong> {{ item.isActive ? 'Si' : 'No' }}</p>
          </article>
        </div>
        <div class="grid two">
          <article class="panel">
            <rrhh-candidate-languages
              [candidateId]="item.id"
              [languages]="item.languages"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-programs
              [candidateId]="item.id"
              [programs]="item.programs"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-education
              [candidateId]="item.id"
              [education]="item.education"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-experience
              [candidateId]="item.id"
              [experience]="item.experience"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel">
            <rrhh-candidate-skills
              [candidateId]="item.id"
              [skills]="item.skills"
              [canEdit]="auth.hasPermission('edit_candidates')"
            />
          </article>
          <article class="panel"><rrhh-candidate-documents [candidate]="item" /></article>
        </div>
      </section>
    } @else {
      <section class="panel">
        <h1>Candidato no encontrado</h1>
        <a class="button" routerLink="/app/candidates">Volver</a>
      </section>
    }
  `,
})
export class CandidateDetailPageComponent {
  @Input('id') candidateId = '';

  constructor(
    readonly auth: AuthService,
    private readonly candidateService: CandidateService,
    private readonly confirmDialog: ConfirmDialogService,
  ) {}

  get candidate() {
    return this.candidateService.find(this.candidateId);
  }

  async deactivate(id: string): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Aplicar baja lógica',
      message: 'El candidato dejará de aparecer en listados activos.',
      confirmText: 'Aplicar baja',
      cancelText: 'Cancelar',
      danger: true,
    });
    if (!confirmed) {
      return;
    }
    this.candidateService.deactivate(id);
  }

  async reactivate(id: string): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Aplicar alta lógica',
      message: 'El candidato volverá a aparecer en listados activos.',
      confirmText: 'Aplicar alta',
      cancelText: 'Cancelar',
    });
    if (!confirmed) {
      return;
    }
    this.candidateService.reactivate(id);
  }
}

// frontend/src/app/features/candidates/pages/candidate-detail-page.tsx
import { useTranslation } from 'react-i18next';
import { Link, useParams } from 'react-router';
import { usePermission, useServices } from '../../../core/di/services-context';
import { useErrorToast } from '../../../core/services/use-error-toast';
import { CandidateCvPreview } from '../components/candidate-cv-preview';
import { CandidateDocuments } from '../components/candidate-documents';
import { CandidateEducation } from '../components/candidate-education';
import { CandidateExperience } from '../components/candidate-experience';
import { CandidateLanguages } from '../components/candidate-languages';
import { CandidatePrograms } from '../components/candidate-programs';
import { CandidateSkills } from '../components/candidate-skills';
import { CandidateTags } from '../components/candidate-tags';
import { CandidateNotes } from '../components/candidate-notes';
import { mailtoHref, telHref } from '../contact-links';
import { useCandidate } from '../use-candidates';

export function CandidateDetailPage() {
  const { t } = useTranslation();
  const { id: candidateId = '' } = useParams<{ id: string }>();
  const { confirmDialogService } = useServices();
  const notifyError = useErrorToast();
  const candidateService = useCandidate(candidateId);
  const item = candidateService.find(candidateId);
  const canEdit = usePermission('candidates.update');
  const aggregate = candidateService.aggregateStatus(candidateId);

  const setActive = async (active: boolean): Promise<void> => {
    if (!item) return;
    const confirmed = await confirmDialogService.confirm({
      title: t(active ? 'candidate.detail.activateTitle' : 'candidate.detail.deactivateTitle'),
      message: t(
        active ? 'candidate.detail.activateMessage' : 'candidate.detail.deactivateMessage',
      ),
      confirmText: t(active ? 'candidate.detail.activate' : 'candidate.detail.deactivate'),
      cancelText: t('candidate.detail.cancel'),
      danger: !active,
    });
    if (!confirmed) return;
    try {
      if (active) await candidateService.reactivate(item.id);
      else await candidateService.deactivate(item.id);
    } catch (error) {
      notifyError(error, t('candidate.detail.stateFailure'));
    }
  };

  if (aggregate === 'loading')
    return (
      <section className="panel">
        <p className="empty-state">{t('candidate.detail.loading')}</p>
      </section>
    );
  if (aggregate === 'error')
    return (
      <section className="panel" data-testid="candidate-detail-error">
        <h1>{t('candidate.detail.loadFailure')}</h1>
        <p className="empty-state">
          {candidateService.error?.message ?? t('candidate.detail.tryLater')}
        </p>
        <Link className="button" to="/app/candidates">
          {t('candidate.detail.back')}
        </Link>
      </section>
    );
  if (!item)
    return (
      <section className="panel">
        <h1>{t('candidate.detail.notFound')}</h1>
        <Link className="button" to="/app/candidates">
          {t('candidate.detail.back')}
        </Link>
      </section>
    );

  return (
    <section className="page">
      <div className="toolbar">
        <div className="page-header">
          <h1>
            {item.firstName} {item.lastName}
          </h1>
          <p className="muted contact-links">
            {item.email ? <a href={mailtoHref(item.email)}>{item.email}</a> : null}
            {item.email && item.phone ? ' · ' : null}
            {item.phone ? <a href={telHref(item.phone)}>{item.phone}</a> : null}
          </p>
        </div>
        <div className="toolbar">
          {canEdit ? (
            <>
              <Link className="button secondary" to={`/app/candidates/${item.id}/edit`}>
                {t('candidate.detail.edit')}
              </Link>
              <button
                className={item.isActive ? 'button danger' : 'button secondary'}
                type="button"
                onClick={() => void setActive(!item.isActive)}
              >
                {t(
                  item.isActive
                    ? 'candidate.detail.logicalDeactivate'
                    : 'candidate.detail.logicalActivate',
                )}
              </button>
            </>
          ) : null}
        </div>
      </div>
      <div className="grid two">
        <article className="panel">
          <h2>{t('candidate.detail.mainData')}</h2>
          <dl className="prop-list">
            <dt>{t('candidate.detail.status')}</dt>
            <dd>{item.status}</dd>
            <dt>{t('candidate.detail.availability')}</dt>
            <dd>{item.availability}</dd>
            <dt>{t('candidate.detail.location')}</dt>
            <dd>
              {item.location} {item.province}
            </dd>
            <dt>{t('candidate.detail.receivedAt')}</dt>
            <dd>{item.receivedAt || t('candidate.detail.pending')}</dd>
            <dt>{t('candidate.detail.reviewDueAt')}</dt>
            <dd>{item.reviewDueAt || t('candidate.detail.pending')}</dd>
          </dl>
          {item.notes ? <p>{item.notes}</p> : null}
        </article>
        <article className="panel">
          <h2>{t('candidate.detail.audit')}</h2>
          <dl className="prop-list">
            <dt>{t('candidate.detail.created')}</dt>
            <dd>{item.createdAt.slice(0, 19)}</dd>
            <dt>{t('candidate.detail.updated')}</dt>
            <dd>{item.updatedAt.slice(0, 19)}</dd>
            <dt>{t('candidate.detail.active')}</dt>
            <dd data-testid="candidate-active">
              {t(item.isActive ? 'candidate.detail.yes' : 'candidate.detail.no')}
            </dd>
          </dl>
        </article>
      </div>
      <div className="grid two">
        <article className="panel">
          <CandidateLanguages candidateId={item.id} languages={item.languages} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidatePrograms candidateId={item.id} programs={item.programs} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateEducation candidateId={item.id} education={item.education} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateExperience
            candidateId={item.id}
            experience={item.experience}
            canEdit={canEdit}
          />
        </article>
        <article className="panel">
          <CandidateSkills candidateId={item.id} skills={item.skills} canEdit={canEdit} />
        </article>
        <article className="panel">
          <CandidateTags candidateId={item.id} tags={item.tags} />
        </article>
        <article className="panel span-all">
          <CandidateNotes candidateId={item.id} initialNotes={item.customNotes} />
        </article>
        <article className="panel">
          <CandidateDocuments candidate={item} />
        </article>
      </div>
      <CandidateCvPreview candidate={item} />
    </section>
  );
}
