// src/app/features/dashboard/dashboard-page.tsx
import { Link } from 'react-router';
import { useCandidates } from '../candidates/use-candidates';

export function DashboardPage() {
  // These counts are cheap enough that plain in-render computation beats
  // memoising with stale-dep risk.
  const candidateService = useCandidates();

  const today = new Date().toISOString().slice(0, 10);
  const month = today.slice(0, 7);

  const active = candidateService.list();
  const activeCount = active.length;
  const inactiveCount = candidateService.list(true).filter((c) => !c.isActive).length;
  const withoutCv = active.filter((c) => c.documents.length === 0).length;
  const pendingReview = active.filter((c) => c.reviewDueAt && c.reviewDueAt < today).length;
  const withPrimaryCv = active.filter((c) => c.documents.some((d) => d.isPrimary)).length;
  const receivedThisMonth = active.filter((c) => c.receivedAt.startsWith(month)).length;

  return (
    <section className="page">
      <div className="toolbar">
        <div className="page-header">
          <h1>Dashboard</h1>
          <p className="muted">Resumen operativo de candidatos y CVs.</p>
        </div>
        <Link className="button" to="/app/candidates/new">
          Alta de candidato
        </Link>
      </div>
      <div className="grid four">
        <article className="panel kpi-card">
          <span className="kpi-label">Candidatos activos</span>
          <span className="kpi-value">{activeCount}</span>
        </article>
        <article className="panel kpi-card">
          <span className="kpi-label">Sin CV adjunto</span>
          <span className="kpi-value">{withoutCv}</span>
        </article>
        <article className="panel kpi-card">
          <span className="kpi-label">Pendientes de revisión</span>
          <span className="kpi-value">{pendingReview}</span>
        </article>
        <article className="panel kpi-card">
          <span className="kpi-label">Recibidos este mes</span>
          <span className="kpi-value">{receivedThisMonth}</span>
        </article>
      </div>

      <div className="grid three">
        <article className="panel stack">
          <h2>Centro operativo</h2>
          <p className="muted">Accesos rápidos para las tareas diarias de RRHH.</p>
          <Link className="button secondary" to="/app/candidates">
            Gestionar listado
          </Link>
          <Link className="button secondary" to="/app/search">
            Búsqueda avanzada
          </Link>
        </article>
        <article className="panel kpi-card">
          <span className="kpi-label">Inactivos</span>
          <span className="kpi-value">{inactiveCount}</span>
        </article>
        <article className="panel kpi-card">
          <span className="kpi-label">Con CV principal</span>
          <span className="kpi-value">{withPrimaryCv}</span>
        </article>
      </div>
    </section>
  );
}

// src/app/features/dashboard/dashboard-page.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CandidateService } from '../candidates/services/candidate.service';

@Component({
  selector: 'rrhh-dashboard-page',
  standalone: true,
  imports: [RouterLink],
  template: `
    <section class="page">
      <div class="toolbar">
        <div class="page-header">
          <h1>Dashboard</h1>
          <p class="muted">Resumen operativo de candidatos y CVs.</p>
        </div>
        <a class="button" routerLink="/app/candidates/new">Alta de candidato</a>
      </div>
      <div class="grid four">
        <article class="panel kpi-card">
          <span class="kpi-label">Candidatos activos</span>
          <span class="kpi-value">{{ activeCount }}</span>
        </article>
        <article class="panel kpi-card">
          <span class="kpi-label">Sin CV adjunto</span>
          <span class="kpi-value">{{ withoutCv }}</span>
        </article>
        <article class="panel kpi-card">
          <span class="kpi-label">Pendientes de revisión</span>
          <span class="kpi-value">{{ pendingReview }}</span>
        </article>
        <article class="panel kpi-card">
          <span class="kpi-label">Recibidos este mes</span>
          <span class="kpi-value">{{ receivedThisMonth }}</span>
        </article>
      </div>

      <div class="grid three">
        <article class="panel stack">
          <h2>Centro operativo</h2>
          <p class="muted">Accesos rápidos para las tareas diarias de RRHH.</p>
          <a class="button secondary" routerLink="/app/candidates">Gestionar listado</a>
          <a class="button secondary" routerLink="/app/search">Búsqueda avanzada</a>
        </article>
        <article class="panel kpi-card">
          <span class="kpi-label">Inactivos</span>
          <span class="kpi-value">{{ inactiveCount }}</span>
        </article>
        <article class="panel kpi-card">
          <span class="kpi-label">Con CV principal</span>
          <span class="kpi-value">{{ withPrimaryCv }}</span>
        </article>
      </div>
    </section>
  `,
})
export class DashboardPageComponent {
  private readonly today = new Date().toISOString().slice(0, 10);
  private readonly month = this.today.slice(0, 7);

  constructor(private readonly candidateService: CandidateService) {}

  get activeCount(): number {
    return this.candidateService.list().length;
  }

  get inactiveCount(): number {
    return this.candidateService.list(true).filter((candidate) => !candidate.isActive).length;
  }

  get withoutCv(): number {
    return this.candidateService.list().filter((candidate) => candidate.documents.length === 0)
      .length;
  }

  get pendingReview(): number {
    return this.candidateService
      .list()
      .filter((candidate) => candidate.reviewDueAt && candidate.reviewDueAt < this.today).length;
  }

  get withPrimaryCv(): number {
    return this.candidateService
      .list()
      .filter((candidate) => candidate.documents.some((document) => document.isPrimary)).length;
  }

  get receivedThisMonth(): number {
    return this.candidateService
      .list()
      .filter((candidate) => candidate.receivedAt.startsWith(this.month)).length;
  }
}
